/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reportes;

import conexion.informe_todos;

/**
 *
 * @author Matrix
 */
public class informes extends javax.swing.JFrame {

    informe_todos i = new informe_todos();
     

  
    public informes() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        txtfecha4 = new javax.swing.JFormattedTextField();
        txtfecha3 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtfecha1 = new javax.swing.JFormattedTextField();
        txtfecha2 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jcMousePanel2 = new jcMousePanel.jcMousePanel();
        jcMousePanel3 = new jcMousePanel.jcMousePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reportes");
        setResizable(false);
        getContentPane().setLayout(null);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Empleado.jpg"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);
        jcMousePanel1.setLayout(null);
        getContentPane().add(jcMousePanel1);
        jcMousePanel1.setBounds(0, 0, 250, 170);

        txtfecha4.setText("//");
        getContentPane().add(txtfecha4);
        txtfecha4.setBounds(290, 280, 110, 20);

        txtfecha3.setText("//");
        getContentPane().add(txtfecha3);
        txtfecha3.setBounds(170, 280, 110, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 0));
        jLabel2.setText("Presupuesto");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 270, 150, 29);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/informes.png"))); // NOI18N
        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 210, 150, 40);

        txtfecha1.setText("//");
        txtfecha1.setToolTipText("");
        getContentPane().add(txtfecha1);
        txtfecha1.setBounds(180, 180, 109, 20);

        txtfecha2.setText("//");
        txtfecha2.setToolTipText("");
        getContentPane().add(txtfecha2);
        txtfecha2.setBounds(300, 180, 109, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 0));
        jLabel1.setText("Factura");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 170, 170, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/informes.png"))); // NOI18N
        jButton2.setText("Imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 310, 150, 40);

        jcMousePanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo.jpg"))); // NOI18N
        jcMousePanel2.setVisibleLogo(false);
        getContentPane().add(jcMousePanel2);
        jcMousePanel2.setBounds(0, 170, 500, 200);

        jcMousePanel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/impuestos.jpg"))); // NOI18N
        jcMousePanel3.setVisibleLogo(false);
        getContentPane().add(jcMousePanel3);
        jcMousePanel3.setBounds(250, 0, 250, 170);

        setSize(new java.awt.Dimension(511, 398));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //        informe_todos i = new informe_todos();

        i.car("SELECT factura, timbrado, usuario, cliente, clientenombre, ruc, direccion, \n"
                + "       telefono, presupuesto, apertura, facturanumero, fecha, tipo, \n"
                + "       monto, estato, codigo, descripcion, idfacdet, cantidad, exenta, \n"
                + "       iva5, iva10, precio, deposito\n"
                + "  FROM v_factura where fecha between  '" + txtfecha1.getText() + "' and '" + txtfecha2.getText() + "';",
                "factura", txtfecha1.getText(), txtfecha2.getText()
        );

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        i.car("SELECT presupuesto, codigo, articulo, idpresudet, cantidad, exenta, \n"
                + "       iva5, iva10, precio, fecha, cliente, nombre, ruc, direccion, \n"
                + "       telefono, monto, estado\n"
                + "  FROM v_presupuessto where fecha  between '" + txtfecha3.getText() + "' and '" + txtfecha4.getText() + "';", "presupuesto", txtfecha3.getText(), txtfecha4.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new informes().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private jcMousePanel.jcMousePanel jcMousePanel2;
    private jcMousePanel.jcMousePanel jcMousePanel3;
    private javax.swing.JFormattedTextField txtfecha1;
    private javax.swing.JFormattedTextField txtfecha2;
    private javax.swing.JFormattedTextField txtfecha3;
    private javax.swing.JFormattedTextField txtfecha4;
    // End of variables declaration//GEN-END:variables
}
