/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import conexion.conexion;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
 
import java.awt.*;
import java.awt.image.*;
import javax.swing.*;
import java.awt.Toolkit;
/**
 *
 * @author Matrix
 */

   

public class inicio extends javax.swing.JDialog {

    int errores = 0;
    conexion bd = new conexion();

    public inicio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        bd.conecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcontraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acceso al Sistema");
        setBackground(new java.awt.Color(255, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(null);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/login.jpg"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);
        jcMousePanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 51));
        jLabel3.setText("Usuario:");
        jcMousePanel1.add(jLabel3);
        jLabel3.setBounds(20, 30, 70, 17);

        txtnombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(0, 204, 51));
        txtnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombre.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        jcMousePanel1.add(txtnombre);
        txtnombre.setBounds(80, 30, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 51));
        jLabel4.setText("Clave:");
        jcMousePanel1.add(jLabel4);
        jLabel4.setBounds(130, 160, 60, 17);

        txtcontraseña.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtcontraseña.setForeground(new java.awt.Color(0, 204, 51));
        txtcontraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcontraseña.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        txtcontraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcontraseñaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcontraseñaKeyTyped(evt);
            }
        });
        jcMousePanel1.add(txtcontraseña);
        txtcontraseña.setBounds(180, 160, 110, 30);

        getContentPane().add(jcMousePanel1);
        jcMousePanel1.setBounds(-10, -10, 360, 240);

        setSize(new java.awt.Dimension(337, 237));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtcontraseña.requestFocus();
        }
    }//GEN-LAST:event_txtnombreKeyPressed

    private void txtnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyReleased
        txtnombre.setText(txtnombre.getText().toUpperCase());
    }//GEN-LAST:event_txtnombreKeyReleased

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        if (txtnombre.getText().length() > 7) {  //ingresa hasta 4 digitos
            evt.consume();

        }
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtcontraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontraseñaKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { //para que pase al siguiente campo

            if (txtnombre.getText().trim().isEmpty()) { //preguntamos si el campo esta vacio
                JOptionPane.showMessageDialog(null, "Debe Ingresar Usuario");
                txtnombre.requestFocus();
                return;

            }

            if (txtcontraseña.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese su Clave");
                txtcontraseña.requestFocus();
                return;
            }
            try {
                // enviamos unsa sentencia a la base de datos y esperamos un resultado
                bd.statement = bd.conexion.createStatement();
                bd.resultado = bd.statement.executeQuery("  SELECT  id_usuario, usu_nombre, usu_clave, id_estado\n"
                        + "  FROM usuario " //vamos a la base de datos y seleccionamos las columnas
                        + "where id_estado=1 and usu_nombre='" + txtnombre.getText() + "' "
                        + "and usu_clave=md5('" + new String(txtcontraseña.getPassword()) + "')");
                if (bd.resultado.next()) {
                    //                       Ingresar();

                    new menu_principal().setVisible(true);
                    menu_principal.txtidusuario.setText(bd.resultado.getString("id_usuario"));

                    dispose();//deshabilitamos el formulario
                } else {
                    int mensaje = JOptionPane.ERROR_MESSAGE;
                    if (mensaje == JOptionPane.ERROR_MESSAGE) {
                        errores = errores + 1;
                        System.out.println(errores);
                        //en caso contrario
                        //emitimos un mensaje de error y vaciamos los campos
                        JOptionPane.showMessageDialog(null, "Verifique sus Datos", "Informe", JOptionPane.ERROR_MESSAGE);
                        txtnombre.requestFocus();
                        txtnombre.setText("");
                        txtcontraseña.setText("");
                    }

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al Ingresar" + e);
            }
            if (errores >= 3) {
                dispose();
                //                try {
                //                    String sql = "UPDATE usuarios\n"
                //                            + "   SET  usu_estado=?\n"
                //                            + " WHERE usu_nombre=?;";
                //                    PreparedStatement p = conex.conexion.prepareStatement(sql);
                //                    p.setBoolean(1, false);
                //                    p.setString(2, txtnombre.getText());
                //                    p.execute();
                //                } catch (Exception e) {
                //                    JOptionPane.showMessageDialog(null, "error al bloquear");
                //                }

            }
        }
    }//GEN-LAST:event_txtcontraseñaKeyPressed

    private void txtcontraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontraseñaKeyTyped

    }//GEN-LAST:event_txtcontraseñaKeyTyped

     public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagen\\icon\\lock_circle_close [#701].png"));


        return retValue;
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                inicio dialog = new inicio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
