/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package referenciales;

import conexion.conexion;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matrix
 */
public class Impuesto extends javax.swing.JFrame {

    String accion = "";
    conexion bd = new conexion();

    public Impuesto() {
        initComponents();
        bd.conecta();
        cargar_tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtcodigo = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnuevo = new javax.swing.JButton();
        btmodificar = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        btguardar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jcMousePanel2 = new jcMousePanel.jcMousePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mant. y Seguridad");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)), "Detalle"));
        jPanel1.setLayout(null);

        txtcodigo.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtcodigo.setForeground(new java.awt.Color(0, 153, 204));
        txtcodigo.setEnabled(false);
        jPanel1.add(txtcodigo);
        txtcodigo.setBounds(140, 20, 60, 30);

        txtdescripcion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtdescripcion.setForeground(new java.awt.Color(0, 153, 204));
        txtdescripcion.setEnabled(false);
        txtdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdescripcionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdescripcionKeyReleased(evt);
            }
        });
        jPanel1.add(txtdescripcion);
        txtdescripcion.setBounds(140, 60, 240, 30);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/impuestos.jpg"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);
        jcMousePanel1.setLayout(null);
        jPanel1.add(jcMousePanel1);
        jcMousePanel1.setBounds(10, 100, 390, 160);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Codigo:");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel9.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 20, 100, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Descripcion:");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel11.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 60, 100, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 270, 410, 270);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)), "......"));
        jPanel2.setLayout(null);

        btnuevo.setBackground(new java.awt.Color(0, 153, 153));
        btnuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnuevo.setForeground(new java.awt.Color(0, 102, 153));
        btnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/nuevo.png"))); // NOI18N
        btnuevo.setText("Nuevo");
        btnuevo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnuevo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnuevo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnuevo);
        btnuevo.setBounds(10, 30, 130, 40);

        btmodificar.setBackground(new java.awt.Color(0, 153, 153));
        btmodificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btmodificar.setForeground(new java.awt.Color(0, 102, 153));
        btmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/editar.png"))); // NOI18N
        btmodificar.setText("Modificar");
        btmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btmodificar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btmodificar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificarActionPerformed(evt);
            }
        });
        jPanel2.add(btmodificar);
        btmodificar.setBounds(10, 70, 130, 40);

        bteliminar.setBackground(new java.awt.Color(0, 153, 153));
        bteliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bteliminar.setForeground(new java.awt.Color(0, 102, 153));
        bteliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/borrar.png"))); // NOI18N
        bteliminar.setText("Eliminar");
        bteliminar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        bteliminar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bteliminar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });
        jPanel2.add(bteliminar);
        bteliminar.setBounds(10, 110, 130, 40);

        btguardar.setBackground(new java.awt.Color(0, 153, 153));
        btguardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btguardar.setForeground(new java.awt.Color(0, 102, 153));
        btguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/Save.png"))); // NOI18N
        btguardar.setText("Guardar");
        btguardar.setEnabled(false);
        btguardar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btguardar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btguardar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarActionPerformed(evt);
            }
        });
        jPanel2.add(btguardar);
        btguardar.setBounds(10, 150, 130, 40);

        btcancelar.setBackground(new java.awt.Color(0, 153, 153));
        btcancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btcancelar.setForeground(new java.awt.Color(0, 102, 153));
        btcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/cancelar.png"))); // NOI18N
        btcancelar.setText("Cancelar");
        btcancelar.setEnabled(false);
        btcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btcancelar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btcancelar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btcancelar);
        btcancelar.setBounds(10, 190, 130, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(430, 270, 160, 270);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setGridColor(new java.awt.Color(255, 255, 255));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMousePressed(evt);
            }
        });
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 570, 200);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Impuesto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 40, 180, 20);

        txtbuscar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtbuscar.setForeground(new java.awt.Color(0, 153, 204));
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtbuscar);
        txtbuscar.setBounds(410, 40, 180, 30);

        jcMousePanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo.jpg"))); // NOI18N
        jcMousePanel2.setVisibleLogo(false);

        javax.swing.GroupLayout jcMousePanel2Layout = new javax.swing.GroupLayout(jcMousePanel2);
        jcMousePanel2.setLayout(jcMousePanel2Layout);
        jcMousePanel2Layout.setHorizontalGroup(
            jcMousePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jcMousePanel2Layout.setVerticalGroup(
            jcMousePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(jcMousePanel2);
        jcMousePanel2.setBounds(-50, -60, 670, 620);

        setSize(new java.awt.Dimension(624, 586));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtdescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescripcionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btguardar.doClick();
        }
    }//GEN-LAST:event_txtdescripcionKeyPressed

    private void txtdescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescripcionKeyReleased
        txtdescripcion.setText(txtdescripcion.getText().toUpperCase());
    }//GEN-LAST:event_txtdescripcionKeyReleased

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
        accion = "nuevo";
        btcancelar.doClick();
        btcancelar.setEnabled(true);
        bd.autonumerico("impuesto", "id_impuesto", txtcodigo);
        limpiar_campos1();
        txtdescripcion.setEnabled(true);
        txtdescripcion.requestFocus();
        bd.deshabilitar_botones(btnuevo, btmodificar, bteliminar, btguardar);
    }//GEN-LAST:event_btnuevoActionPerformed

    private void btmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificarActionPerformed
        if (txtcodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro", "Informe", JOptionPane.INFORMATION_MESSAGE);
        } else {
            accion = "modificar";
            btcancelar.setEnabled(true);
            bd.deshabilitar_botones(btnuevo, btmodificar, bteliminar, btguardar);
            habilitar_campos();
            txtdescripcion.requestFocus();

        }
    }//GEN-LAST:event_btmodificarActionPerformed

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
        if (txtcodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro", "Informe", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int mensaje = JOptionPane.showConfirmDialog(null, "Desea eliminar el registro", "Informe", JOptionPane.YES_NO_OPTION);
            if (mensaje == JOptionPane.YES_OPTION) {
                try {
                    String sql = "delete from impuesto where id_impuesto=?";
                    PreparedStatement eli = bd.conexion.prepareStatement(sql);
                    eli.setInt(1, Integer.parseInt(txtcodigo.getText()));
                    eli.execute();

                    cargar_tabla();
                    limpiar_campos();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al eliminar la tabla" + e);
                }
            }

        }
    }//GEN-LAST:event_bteliminarActionPerformed

    private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarActionPerformed
        if (txtdescripcion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe Ingresar Datos", "Informe", JOptionPane.INFORMATION_MESSAGE);
            txtdescripcion.requestFocus();
            return;
        }

        grabar();
    }//GEN-LAST:event_btguardarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        accion = "";
        btcancelar.setEnabled(false);
        bd.habilitar_botones(btnuevo, btmodificar, bteliminar, btguardar);
        limpiar_campos();
        deshabilitar_campos();
        txtbuscar.requestFocus();
    }//GEN-LAST:event_btcancelarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        if (accion.equals("")) {
            String vid = tabla.getValueAt(tabla.getSelectedRow(), 0).toString();
            txtcodigo.setText(vid);
            recuperar_datos();

        }
    }//GEN-LAST:event_tablaMouseClicked

    private void tablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMousePressed
        if (accion.equals("")) {
            String vid = tabla.getValueAt(tabla.getSelectedRow(), 0).toString();
            txtcodigo.setText(vid);
            recuperar_datos();

        }
    }//GEN-LAST:event_tablaMousePressed

    private void tablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyPressed
        if (accion.equals("")) {
            String vid = tabla.getValueAt(tabla.getSelectedRow(), 0).toString();
            txtcodigo.setText(vid);
            recuperar_datos();

        }
    }//GEN-LAST:event_tablaKeyPressed

    private void tablaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyReleased
        if (accion.equals("")) {
            String vid = tabla.getValueAt(tabla.getSelectedRow(), 0).toString();
            txtcodigo.setText(vid);
            recuperar_datos();

        }
    }//GEN-LAST:event_tablaKeyReleased

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (tabla.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No existe ningun registro");
                txtbuscar.setText("");
                cargar_tabla();
                txtbuscar.requestFocus();
            } else {
                tabla.getSelectionModel().setSelectionInterval(0, 0);
                tabla.requestFocus();

            }
        }
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        cargar_tabla();
    }//GEN-LAST:event_txtbuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Impuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Impuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Impuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Impuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Impuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btcancelar;
    public javax.swing.JButton bteliminar;
    public javax.swing.JButton btguardar;
    public javax.swing.JButton btmodificar;
    public javax.swing.JButton btnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private jcMousePanel.jcMousePanel jcMousePanel2;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtbuscar;
    public javax.swing.JTextField txtcodigo;
    public javax.swing.JTextField txtdescripcion;
    // End of variables declaration//GEN-END:variables

    private void cargar_tabla() {
        DefaultTableModel tab = (DefaultTableModel) tabla.getModel();
        tab.setRowCount(0);
        try {
            // ilike busca las letras por mayusculas y minisculas
            bd.listar_datos("SELECT id_impuesto, imp_descri\n"
                    + "  FROM impuesto where id_impuesto::text like'%" + txtbuscar.getText() + "%' or imp_descri ilike '%" + txtbuscar.getText() + "%';");
            while (bd.resultado.next()) {
                tab.addRow(new Object[]{bd.resultado.getString("id_impuesto"),
                    bd.resultado.getString("imp_descri")});

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar la tabla" + e);
        }
    }

    private void limpiar_campos1() {
        txtdescripcion.setText("");
    }

    private void limpiar_campos() {
        txtcodigo.setText("");
        txtdescripcion.setText("");
    }

    private void deshabilitar_campos() {
        txtdescripcion.setEnabled(false);
    }

    private void habilitar_campos() {
        txtdescripcion.setEnabled(true);
    }

    private void grabar() {
        if (accion.equals("nuevo")) {
            //guardar
            try {
                String sql = "INSERT INTO impuesto(\n"
                        + "            id_impuesto, imp_descri)\n"
                        + "    VALUES (?, ?);";
                PreparedStatement p = bd.conexion.prepareStatement(sql);
                p.setInt(1, Integer.parseInt(txtcodigo.getText()));
                p.setString(2, txtdescripcion.getText());
                p.execute();
                cargar_tabla();
                btcancelar.doClick();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al guardar los datos" + e);
            }

        } else {
            //modificar
            try {
                String sql = "UPDATE impuesto\n"
                        + "   SET  imp_descri=?\n"
                        + " WHERE id_impuesto=?;";
                PreparedStatement p = bd.conexion.prepareStatement(sql);
                p.setInt(2, Integer.parseInt(txtcodigo.getText()));
                p.setString(1, txtdescripcion.getText());
                p.execute();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al modificar el registro de stock" + e);
            }

            cargar_tabla();
            btcancelar.doClick();

        }

    }

    private void recuperar_datos() {
        try {
            bd.listar_datos("SELECT id_impuesto, imp_descri\n"
                    + "  FROM impuesto where id_impuesto=" + txtcodigo.getText() + ";");
            if (bd.resultado.next()) {
                txtdescripcion.setText(bd.resultado.getString("imp_descri"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al recuperar la tabla" + e);
        }
    }
}
