/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package referenciales;

/**
 *
 * @author Matrix
 */
public class proveedores extends javax.swing.JFrame {

    /**
     * Creates new form proveedores
     */
    public proveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtruc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtidciudad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtciudad = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcelular = new javax.swing.JTextField();
        jcMousePanel2 = new jcMousePanel.jcMousePanel();
        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jPanel1 = new javax.swing.JPanel();
        btnuevo = new javax.swing.JButton();
        btmodificar = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        btguardar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        jcMousePanel3 = new jcMousePanel.jcMousePanel();
        jPanel3 = new javax.swing.JPanel();
        btnuevo1 = new javax.swing.JButton();
        btmodificar1 = new javax.swing.JButton();
        bteliminar1 = new javax.swing.JButton();
        btguardar1 = new javax.swing.JButton();
        btcancelar1 = new javax.swing.JButton();
        txtbuscar1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtcodigo1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnombre1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtruc1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtdireccion1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtidciudad1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtestado1 = new javax.swing.JTextField();
        txttelefono1 = new javax.swing.JTextField();
        txtciudad1 = new javax.swing.JTextField();
        txtapellido1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtcelular1 = new javax.swing.JTextField();
        jcMousePanel4 = new jcMousePanel.jcMousePanel();
        jcMousePanel5 = new jcMousePanel.jcMousePanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mant. y Seguridad");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Proveedor");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 180, 20);

        tabla.setBackground(new java.awt.Color(0, 153, 153));
        tabla.setForeground(new java.awt.Color(153, 255, 255));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Razon Social", "Ruc", "Direccion", "Celular", "Telefono", "Ciudad", "Correo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setSelectionForeground(new java.awt.Color(0, 153, 255));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 740, 210);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 255, 255));
        jLabel10.setText("Buscar");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(490, 30, 70, 14);

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtbuscar);
        txtbuscar.setBounds(540, 30, 220, 20);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Detalles"));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Id:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 50, 80, 20);

        txtcodigo.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtcodigo.setForeground(new java.awt.Color(0, 153, 153));
        jPanel2.add(txtcodigo);
        txtcodigo.setBounds(110, 50, 50, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Razon Social");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 80, 80, 20);

        txtnombre.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(0, 153, 153));
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        jPanel2.add(txtnombre);
        txtnombre.setBounds(110, 80, 170, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Ruc:");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 110, 80, 20);

        txtruc.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtruc.setForeground(new java.awt.Color(0, 153, 153));
        txtruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtrucKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrucKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrucKeyTyped(evt);
            }
        });
        jPanel2.add(txtruc);
        txtruc.setBounds(110, 110, 170, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Direccion:");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel8.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 140, 80, 20);

        txtdireccion.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtdireccion.setForeground(new java.awt.Color(0, 153, 153));
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdireccionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdireccionKeyReleased(evt);
            }
        });
        jPanel2.add(txtdireccion);
        txtdireccion.setBounds(110, 140, 170, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Telefono:");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel9.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 200, 80, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Ciudad:");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel11.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 260, 80, 20);

        txtidciudad.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtidciudad.setForeground(new java.awt.Color(0, 153, 153));
        txtidciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidciudadKeyPressed(evt);
            }
        });
        jPanel2.add(txtidciudad);
        txtidciudad.setBounds(110, 260, 50, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Estado:");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel12.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 290, 80, 20);

        txtestado.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtestado.setForeground(new java.awt.Color(0, 153, 153));
        txtestado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtestadoKeyPressed(evt);
            }
        });
        jPanel2.add(txtestado);
        txtestado.setBounds(110, 290, 170, 20);

        txttelefono.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txttelefono.setForeground(new java.awt.Color(0, 153, 153));
        txttelefono.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txttelefonoCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelefonoKeyPressed(evt);
            }
        });
        jPanel2.add(txttelefono);
        txttelefono.setBounds(110, 200, 170, 20);

        txtciudad.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtciudad.setForeground(new java.awt.Color(0, 153, 153));
        txtciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtciudadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtciudadKeyReleased(evt);
            }
        });
        jPanel2.add(txtciudad);
        txtciudad.setBounds(170, 260, 110, 20);

        txtapellido.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtapellido.setForeground(new java.awt.Color(0, 153, 153));
        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtapellidoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtapellidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidoKeyTyped(evt);
            }
        });
        jPanel2.add(txtapellido);
        txtapellido.setBounds(110, 230, 170, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Correo:");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 230, 80, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText(" Celular:");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel13.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 170, 80, 20);

        txtcelular.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtcelular.setForeground(new java.awt.Color(0, 153, 153));
        txtcelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcelularKeyPressed(evt);
            }
        });
        jPanel2.add(txtcelular);
        txtcelular.setBounds(110, 170, 170, 20);

        jcMousePanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/mercaderias.jpg"))); // NOI18N
        jcMousePanel2.setVisibleLogo(false);
        jPanel2.add(jcMousePanel2);
        jcMousePanel2.setBounds(310, 30, 220, 140);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/nota remision.JPG"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);
        jPanel2.add(jcMousePanel1);
        jcMousePanel1.setBounds(310, 170, 230, 140);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 270, 560, 340);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "..........."));
        jPanel1.setLayout(null);

        btnuevo.setBackground(new java.awt.Color(0, 0, 0));
        btnuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnuevo.setForeground(new java.awt.Color(0, 153, 255));
        btnuevo.setText("Nuevo");
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnuevo);
        btnuevo.setBounds(20, 80, 130, 40);

        btmodificar.setBackground(new java.awt.Color(0, 0, 0));
        btmodificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btmodificar.setForeground(new java.awt.Color(0, 153, 255));
        btmodificar.setText("Modificar");
        btmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificarActionPerformed(evt);
            }
        });
        jPanel1.add(btmodificar);
        btmodificar.setBounds(20, 120, 130, 40);

        bteliminar.setBackground(new java.awt.Color(0, 0, 0));
        bteliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bteliminar.setForeground(new java.awt.Color(0, 153, 255));
        bteliminar.setText("Eliminar");
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });
        jPanel1.add(bteliminar);
        bteliminar.setBounds(20, 160, 130, 40);

        btguardar.setBackground(new java.awt.Color(0, 0, 0));
        btguardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btguardar.setForeground(new java.awt.Color(0, 153, 255));
        btguardar.setText("Guardar");
        btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btguardar);
        btguardar.setBounds(20, 200, 130, 40);

        btcancelar.setBackground(new java.awt.Color(0, 0, 0));
        btcancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btcancelar.setForeground(new java.awt.Color(0, 153, 255));
        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btcancelar);
        btcancelar.setBounds(20, 240, 130, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(590, 270, 170, 340);

        jcMousePanel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo.jpg"))); // NOI18N
        jcMousePanel3.setVisibleLogo(false);
        jcMousePanel3.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "..........."));
        jPanel3.setLayout(null);

        btnuevo1.setBackground(new java.awt.Color(0, 0, 0));
        btnuevo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnuevo1.setForeground(new java.awt.Color(0, 153, 255));
        btnuevo1.setText("Nuevo");
        btnuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevo1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnuevo1);
        btnuevo1.setBounds(20, 80, 130, 40);

        btmodificar1.setBackground(new java.awt.Color(0, 0, 0));
        btmodificar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btmodificar1.setForeground(new java.awt.Color(0, 153, 255));
        btmodificar1.setText("Modificar");
        btmodificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btmodificar1);
        btmodificar1.setBounds(20, 120, 130, 40);

        bteliminar1.setBackground(new java.awt.Color(0, 0, 0));
        bteliminar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bteliminar1.setForeground(new java.awt.Color(0, 153, 255));
        bteliminar1.setText("Eliminar");
        bteliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminar1ActionPerformed(evt);
            }
        });
        jPanel3.add(bteliminar1);
        bteliminar1.setBounds(20, 160, 130, 40);

        btguardar1.setBackground(new java.awt.Color(0, 0, 0));
        btguardar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btguardar1.setForeground(new java.awt.Color(0, 153, 255));
        btguardar1.setText("Guardar");
        btguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btguardar1);
        btguardar1.setBounds(20, 200, 130, 40);

        btcancelar1.setBackground(new java.awt.Color(0, 0, 0));
        btcancelar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btcancelar1.setForeground(new java.awt.Color(0, 153, 255));
        btcancelar1.setText("Cancelar");
        btcancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btcancelar1);
        btcancelar1.setBounds(20, 240, 130, 40);

        jcMousePanel3.add(jPanel3);
        jPanel3.setBounds(590, 270, 170, 340);

        txtbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscar1ActionPerformed(evt);
            }
        });
        txtbuscar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscar1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscar1KeyReleased(evt);
            }
        });
        jcMousePanel3.add(txtbuscar1);
        txtbuscar1.setBounds(540, 30, 220, 20);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Detalles"));
        jPanel4.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Id:");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel5.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jLabel5);
        jLabel5.setBounds(20, 50, 80, 20);

        txtcodigo1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtcodigo1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel4.add(txtcodigo1);
        txtcodigo1.setBounds(110, 50, 50, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Razon Social");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel6.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jLabel6);
        jLabel6.setBounds(20, 80, 80, 20);

        txtnombre1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtnombre1.setForeground(new java.awt.Color(0, 153, 153));
        txtnombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombre1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombre1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombre1KeyTyped(evt);
            }
        });
        jPanel4.add(txtnombre1);
        txtnombre1.setBounds(110, 80, 170, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Ruc:");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel14.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jLabel14);
        jLabel14.setBounds(20, 110, 80, 20);

        txtruc1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtruc1.setForeground(new java.awt.Color(0, 153, 153));
        txtruc1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtruc1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtruc1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtruc1KeyTyped(evt);
            }
        });
        jPanel4.add(txtruc1);
        txtruc1.setBounds(110, 110, 170, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Direccion:");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel15.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jLabel15);
        jLabel15.setBounds(20, 140, 80, 20);

        txtdireccion1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtdireccion1.setForeground(new java.awt.Color(0, 153, 153));
        txtdireccion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdireccion1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdireccion1KeyReleased(evt);
            }
        });
        jPanel4.add(txtdireccion1);
        txtdireccion1.setBounds(110, 140, 170, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Telefono:");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel16.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jLabel16);
        jLabel16.setBounds(20, 200, 80, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Ciudad:");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel17.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jLabel17);
        jLabel17.setBounds(20, 260, 80, 20);

        txtidciudad1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtidciudad1.setForeground(new java.awt.Color(0, 153, 153));
        txtidciudad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidciudad1KeyPressed(evt);
            }
        });
        jPanel4.add(txtidciudad1);
        txtidciudad1.setBounds(110, 260, 50, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Estado:");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel18.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jLabel18);
        jLabel18.setBounds(20, 290, 80, 20);

        txtestado1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtestado1.setForeground(new java.awt.Color(0, 153, 153));
        txtestado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtestado1KeyPressed(evt);
            }
        });
        jPanel4.add(txtestado1);
        txtestado1.setBounds(110, 290, 170, 20);

        txttelefono1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txttelefono1.setForeground(new java.awt.Color(0, 153, 153));
        txttelefono1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txttelefono1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txttelefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelefono1KeyPressed(evt);
            }
        });
        jPanel4.add(txttelefono1);
        txttelefono1.setBounds(110, 200, 170, 20);

        txtciudad1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtciudad1.setForeground(new java.awt.Color(0, 153, 153));
        txtciudad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtciudad1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtciudad1KeyReleased(evt);
            }
        });
        jPanel4.add(txtciudad1);
        txtciudad1.setBounds(170, 260, 110, 20);

        txtapellido1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtapellido1.setForeground(new java.awt.Color(0, 153, 153));
        txtapellido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtapellido1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtapellido1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellido1KeyTyped(evt);
            }
        });
        jPanel4.add(txtapellido1);
        txtapellido1.setBounds(110, 230, 170, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Correo:");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel19.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jLabel19);
        jLabel19.setBounds(20, 230, 80, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText(" Celular:");
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel20.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jLabel20);
        jLabel20.setBounds(20, 170, 80, 20);

        txtcelular1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtcelular1.setForeground(new java.awt.Color(0, 153, 153));
        txtcelular1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcelular1KeyPressed(evt);
            }
        });
        jPanel4.add(txtcelular1);
        txtcelular1.setBounds(110, 170, 170, 20);

        jcMousePanel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/mercaderias.jpg"))); // NOI18N
        jcMousePanel4.setVisibleLogo(false);
        jPanel4.add(jcMousePanel4);
        jcMousePanel4.setBounds(310, 30, 220, 140);

        jcMousePanel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/nota remision.JPG"))); // NOI18N
        jcMousePanel5.setVisibleLogo(false);
        jPanel4.add(jcMousePanel5);
        jcMousePanel5.setBounds(310, 170, 230, 140);

        jcMousePanel3.add(jPanel4);
        jPanel4.setBounds(20, 270, 560, 340);

        tabla1.setBackground(new java.awt.Color(0, 153, 153));
        tabla1.setForeground(new java.awt.Color(153, 255, 255));
        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Razon Social", "Ruc", "Direccion", "Celular", "Telefono", "Ciudad", "Correo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla1.setSelectionForeground(new java.awt.Color(0, 153, 255));
        tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla1MouseClicked(evt);
            }
        });
        tabla1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabla1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabla1);

        jcMousePanel3.add(jScrollPane2);
        jScrollPane2.setBounds(20, 50, 740, 210);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 204, 204));
        jLabel21.setText("Proveedor");
        jcMousePanel3.add(jLabel21);
        jLabel21.setBounds(30, 10, 180, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 255, 255));
        jLabel22.setText("Buscar");
        jcMousePanel3.add(jLabel22);
        jLabel22.setBounds(490, 30, 70, 14);

        getContentPane().add(jcMousePanel3);
        jcMousePanel3.setBounds(0, 0, 790, 630);

        setSize(new java.awt.Dimension(756, 658));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        //        if (accion.equals("")) {
            //            String vid = tabla.getValueAt(tabla.getSelectedRow(), 0).toString();
            //            txtcodigo.setText(vid);
            //            controlcli.recuperar_datos();
            //
            //        }
    }//GEN-LAST:event_tablaMouseClicked

    private void tablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyPressed
        //        if (accion.equals("")) {
            //            String vid = tabla.getValueAt(tabla.getSelectedRow(), 0).toString();
            //            txtcodigo.setText(vid);
            //            controlcli.recuperar_datos();
            //
            //        }
    }//GEN-LAST:event_tablaKeyPressed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        //        txtbuscar.setText(txtbuscar.getText().toUpperCase());
        //        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //            if (tabla.getRowCount() == 0) {   //si la tabla no tiene ningun registro la fila esta en cero
                //                JOptionPane.showMessageDialog(null, "No existe Datos", "Informe", JOptionPane.ERROR_MESSAGE);
                //                txtbuscar.setText("");
                //                controlcli.cargartabla();
                //                txtbuscar.requestFocus();
                //            } else {
                //                tabla.getSelectionModel().setSelectionInterval(0, 0);
                //                tabla.requestFocus();
                //            }
            //        }
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        //        controlcli.cargartabla();
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void txtnombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyPressed
        //        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //            txtapellido.requestFocus();
            //        }
    }//GEN-LAST:event_txtnombreKeyPressed

    private void txtnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyReleased
        //        txtnombre.setText(txtnombre.getText().toUpperCase());
    }//GEN-LAST:event_txtnombreKeyReleased

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        //        if (Character.isDigit(evt.getKeyChar()) == true) {
            //            evt.consume();
            //        }
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtrucKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrucKeyPressed
        //        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //            txtdireccion.requestFocus();
            //        }
    }//GEN-LAST:event_txtrucKeyPressed

    private void txtrucKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrucKeyReleased
        //        txtruc.setText(txtruc.getText().toUpperCase());
    }//GEN-LAST:event_txtrucKeyReleased

    private void txtrucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrucKeyTyped
        //        if (Character.isDigit(evt.getKeyChar()) == false) {
            //            evt.consume();
            //        }
    }//GEN-LAST:event_txtrucKeyTyped

    private void txtdireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyPressed
        //        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //            txtcelular.requestFocus();
            //        }
    }//GEN-LAST:event_txtdireccionKeyPressed

    private void txtdireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyReleased
        //        txtdireccion.setText(txtdireccion.getText().toUpperCase());
    }//GEN-LAST:event_txtdireccionKeyReleased

    private void txtidciudadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidciudadKeyPressed
        //        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //            if (txtidciudad.getText().isEmpty()) {
                //                //buscador
                //                new buscadores.buscador_ciudad1(null, true).setVisible(true);
                //
                //            } else {
                //
                //                controlcli.recuperar_ciudad();
                //                btguardar.doClick();
                //
                //            }
            //        }
    }//GEN-LAST:event_txtidciudadKeyPressed

    private void txtestadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtestadoKeyPressed

    }//GEN-LAST:event_txtestadoKeyPressed

    private void txttelefonoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txttelefonoCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoCaretPositionChanged

    private void txttelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyPressed
        //        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //            txtidciudad.requestFocus();
            //        }
    }//GEN-LAST:event_txttelefonoKeyPressed

    private void txtciudadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtciudadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtciudadKeyPressed

    private void txtciudadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtciudadKeyReleased
        //        txtciudad.setText(txtciudad.getText().toUpperCase());
    }//GEN-LAST:event_txtciudadKeyReleased

    private void txtapellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyPressed
        //        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //            txtci.requestFocus();
            //        }
    }//GEN-LAST:event_txtapellidoKeyPressed

    private void txtapellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyReleased
        //       txtapellido.setText(txtapellido.getText().toUpperCase());
    }//GEN-LAST:event_txtapellidoKeyReleased

    private void txtapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoKeyTyped

    private void txtcelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcelularKeyPressed
        //        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //            txttelefono.requestFocus();
            //        }
    }//GEN-LAST:event_txtcelularKeyPressed

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
        //        btcancelar.doClick();
        //        btcancelar.setEnabled(true);
        //        //        btguardar.setEnabled(true);
        //        accion = "nuevo";
        //        controlcli.autonumerico();
        //        controlcli.limpiarcamposnuevo();
        //        //habilitamos los campos
        //        controlcli.habilitarcampos();
        //
        //        txtnombre.requestFocus();
        //        controlcli.deshabilitarbotones();
    }//GEN-LAST:event_btnuevoActionPerformed

    private void btmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificarActionPerformed
        //        if (txtcodigo.getText().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Seleccione un registro", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //        } else {
            //            accion = "modificar";
            //            txtestado.setEnabled(true);
            //            btcancelar.setEnabled(true);
            //            controlcli.deshabilitarbotones();
            //            controlcli.habilitarcampos();
            //            txtnombre.requestFocus();
            //
            //        }
    }//GEN-LAST:event_btmodificarActionPerformed

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
        //        if (txtcodigo.getText().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Seleccione un registro", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //        } else {
            //            controlcli.eliminar();
            //        }
    }//GEN-LAST:event_bteliminarActionPerformed

    private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarActionPerformed
        //        if (txtnombre.getText().trim().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Debe Ingresar Nombre", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //            txtnombre.requestFocus();
            //            return;
            //        }
        //         if (txtci.getText().trim().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Debe Ingresar C.I", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //            txtci.requestFocus();
            //            return;
            //        }
        //        if (txtruc.getText().trim().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Debe Ingresar Ruc", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //            txtruc.requestFocus();
            //            return;
            //        }
        //
        //        if (txtdireccion.getText().trim().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Debe Ingresar Direccion", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //            txtdireccion.requestFocus();
            //            return;
            //        }
        //        if (txttelefono.getText().trim().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Debe Ingresar Telefono", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //            txttelefono.requestFocus();
            //            return;
            //        }
        //         if (txtcelular.getText().trim().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Debe Ingresar Celular", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //            txtcelular.requestFocus();
            //            return;
            //        }
        //        if (txtidciudad.getText().trim().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Debe Ingresar Ciudad", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //            txtidciudad.requestFocus();
            //            txtciudad.setText("");
            //            return;
            //        }
        //
        //        if (txtestado.getText().trim().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Debe Ingresar Estado", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //            txtestado.requestFocus();
            //            return;
            //        }
        //        grabar();
    }//GEN-LAST:event_btguardarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        //        accion = "";
        //        btcancelar.setEnabled(false);
        //        controlcli.habilitarbotones();
        //        //limpiamos los campos
        //        controlcli.limpiarcampos();
        //        //deshabilitamos los campos
        //        controlcli.deshabilitarcampos();
    }//GEN-LAST:event_btcancelarActionPerformed

    private void btnuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevo1ActionPerformed
        //        btcancelar.doClick();
        //        btcancelar.setEnabled(true);
        //        //        btguardar.setEnabled(true);
        //        accion = "nuevo";
        //        controlcli.autonumerico();
        //        controlcli.limpiarcamposnuevo();
        //        //habilitamos los campos
        //        controlcli.habilitarcampos();
        //
        //        txtnombre.requestFocus();
        //        controlcli.deshabilitarbotones();
    }//GEN-LAST:event_btnuevo1ActionPerformed

    private void btmodificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificar1ActionPerformed
        //        if (txtcodigo.getText().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Seleccione un registro", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //        } else {
            //            accion = "modificar";
            //            txtestado.setEnabled(true);
            //            btcancelar.setEnabled(true);
            //            controlcli.deshabilitarbotones();
            //            controlcli.habilitarcampos();
            //            txtnombre.requestFocus();
            //
            //        }
    }//GEN-LAST:event_btmodificar1ActionPerformed

    private void bteliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminar1ActionPerformed
        //        if (txtcodigo.getText().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Seleccione un registro", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //        } else {
            //            controlcli.eliminar();
            //        }
    }//GEN-LAST:event_bteliminar1ActionPerformed

    private void btguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardar1ActionPerformed
        //        if (txtnombre.getText().trim().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Debe Ingresar Nombre", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //            txtnombre.requestFocus();
            //            return;
            //        }
        //         if (txtci.getText().trim().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Debe Ingresar C.I", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //            txtci.requestFocus();
            //            return;
            //        }
        //        if (txtruc.getText().trim().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Debe Ingresar Ruc", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //            txtruc.requestFocus();
            //            return;
            //        }
        //
        //        if (txtdireccion.getText().trim().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Debe Ingresar Direccion", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //            txtdireccion.requestFocus();
            //            return;
            //        }
        //        if (txttelefono.getText().trim().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Debe Ingresar Telefono", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //            txttelefono.requestFocus();
            //            return;
            //        }
        //         if (txtcelular.getText().trim().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Debe Ingresar Celular", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //            txtcelular.requestFocus();
            //            return;
            //        }
        //        if (txtidciudad.getText().trim().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Debe Ingresar Ciudad", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //            txtidciudad.requestFocus();
            //            txtciudad.setText("");
            //            return;
            //        }
        //
        //        if (txtestado.getText().trim().isEmpty()) {
            //            JOptionPane.showMessageDialog(null, "Debe Ingresar Estado", "Informe", JOptionPane.INFORMATION_MESSAGE);
            //            txtestado.requestFocus();
            //            return;
            //        }
        //        grabar();
    }//GEN-LAST:event_btguardar1ActionPerformed

    private void btcancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelar1ActionPerformed
        //        accion = "";
        //        btcancelar.setEnabled(false);
        //        controlcli.habilitarbotones();
        //        //limpiamos los campos
        //        controlcli.limpiarcampos();
        //        //deshabilitamos los campos
        //        controlcli.deshabilitarcampos();
    }//GEN-LAST:event_btcancelar1ActionPerformed

    private void txtbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscar1ActionPerformed

    private void txtbuscar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscar1KeyPressed
        //        txtbuscar.setText(txtbuscar.getText().toUpperCase());
        //        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //            if (tabla.getRowCount() == 0) {   //si la tabla no tiene ningun registro la fila esta en cero
                //                JOptionPane.showMessageDialog(null, "No existe Datos", "Informe", JOptionPane.ERROR_MESSAGE);
                //                txtbuscar.setText("");
                //                controlcli.cargartabla();
                //                txtbuscar.requestFocus();
                //            } else {
                //                tabla.getSelectionModel().setSelectionInterval(0, 0);
                //                tabla.requestFocus();
                //            }
            //        }
    }//GEN-LAST:event_txtbuscar1KeyPressed

    private void txtbuscar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscar1KeyReleased
        //        controlcli.cargartabla();
    }//GEN-LAST:event_txtbuscar1KeyReleased

    private void txtnombre1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombre1KeyPressed
        //        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //            txtapellido.requestFocus();
            //        }
    }//GEN-LAST:event_txtnombre1KeyPressed

    private void txtnombre1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombre1KeyReleased
        //        txtnombre.setText(txtnombre.getText().toUpperCase());
    }//GEN-LAST:event_txtnombre1KeyReleased

    private void txtnombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombre1KeyTyped
        //        if (Character.isDigit(evt.getKeyChar()) == true) {
            //            evt.consume();
            //        }
    }//GEN-LAST:event_txtnombre1KeyTyped

    private void txtruc1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtruc1KeyPressed
        //        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //            txtdireccion.requestFocus();
            //        }
    }//GEN-LAST:event_txtruc1KeyPressed

    private void txtruc1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtruc1KeyReleased
        //        txtruc.setText(txtruc.getText().toUpperCase());
    }//GEN-LAST:event_txtruc1KeyReleased

    private void txtruc1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtruc1KeyTyped
        //        if (Character.isDigit(evt.getKeyChar()) == false) {
            //            evt.consume();
            //        }
    }//GEN-LAST:event_txtruc1KeyTyped

    private void txtdireccion1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccion1KeyPressed
        //        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //            txtcelular.requestFocus();
            //        }
    }//GEN-LAST:event_txtdireccion1KeyPressed

    private void txtdireccion1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccion1KeyReleased
        //        txtdireccion.setText(txtdireccion.getText().toUpperCase());
    }//GEN-LAST:event_txtdireccion1KeyReleased

    private void txtidciudad1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidciudad1KeyPressed
        //        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //            if (txtidciudad.getText().isEmpty()) {
                //                //buscador
                //                new buscadores.buscador_ciudad1(null, true).setVisible(true);
                //
                //            } else {
                //
                //                controlcli.recuperar_ciudad();
                //                btguardar.doClick();
                //
                //            }
            //        }
    }//GEN-LAST:event_txtidciudad1KeyPressed

    private void txtestado1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtestado1KeyPressed

    }//GEN-LAST:event_txtestado1KeyPressed

    private void txttelefono1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txttelefono1CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefono1CaretPositionChanged

    private void txttelefono1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefono1KeyPressed
        //        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //            txtidciudad.requestFocus();
            //        }
    }//GEN-LAST:event_txttelefono1KeyPressed

    private void txtciudad1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtciudad1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtciudad1KeyPressed

    private void txtciudad1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtciudad1KeyReleased
        //        txtciudad.setText(txtciudad.getText().toUpperCase());
    }//GEN-LAST:event_txtciudad1KeyReleased

    private void txtapellido1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellido1KeyPressed
        //        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //            txtci.requestFocus();
            //        }
    }//GEN-LAST:event_txtapellido1KeyPressed

    private void txtapellido1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellido1KeyReleased
        //       txtapellido.setText(txtapellido.getText().toUpperCase());
    }//GEN-LAST:event_txtapellido1KeyReleased

    private void txtapellido1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellido1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellido1KeyTyped

    private void txtcelular1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcelular1KeyPressed
        //        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //            txttelefono.requestFocus();
            //        }
    }//GEN-LAST:event_txtcelular1KeyPressed

    private void tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla1MouseClicked
        //        if (accion.equals("")) {
            //            String vid = tabla.getValueAt(tabla.getSelectedRow(), 0).toString();
            //            txtcodigo.setText(vid);
            //            controlcli.recuperar_datos();
            //
            //        }
    }//GEN-LAST:event_tabla1MouseClicked

    private void tabla1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla1KeyPressed
        //        if (accion.equals("")) {
            //            String vid = tabla.getValueAt(tabla.getSelectedRow(), 0).toString();
            //            txtcodigo.setText(vid);
            //            controlcli.recuperar_datos();
            //
            //        }
    }//GEN-LAST:event_tabla1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btcancelar;
    public javax.swing.JButton btcancelar1;
    public javax.swing.JButton bteliminar;
    public javax.swing.JButton bteliminar1;
    public javax.swing.JButton btguardar;
    public javax.swing.JButton btguardar1;
    public javax.swing.JButton btmodificar;
    public javax.swing.JButton btmodificar1;
    public javax.swing.JButton btnuevo;
    public javax.swing.JButton btnuevo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private jcMousePanel.jcMousePanel jcMousePanel2;
    private jcMousePanel.jcMousePanel jcMousePanel3;
    private jcMousePanel.jcMousePanel jcMousePanel4;
    private jcMousePanel.jcMousePanel jcMousePanel5;
    public javax.swing.JTable tabla;
    public javax.swing.JTable tabla1;
    public javax.swing.JTextField txtapellido;
    public javax.swing.JTextField txtapellido1;
    public javax.swing.JTextField txtbuscar;
    public javax.swing.JTextField txtbuscar1;
    public javax.swing.JTextField txtcelular;
    public javax.swing.JTextField txtcelular1;
    public static javax.swing.JTextField txtciudad;
    public static javax.swing.JTextField txtciudad1;
    public javax.swing.JTextField txtcodigo;
    public javax.swing.JTextField txtcodigo1;
    public javax.swing.JTextField txtdireccion;
    public javax.swing.JTextField txtdireccion1;
    public javax.swing.JTextField txtestado;
    public javax.swing.JTextField txtestado1;
    public static javax.swing.JTextField txtidciudad;
    public static javax.swing.JTextField txtidciudad1;
    public javax.swing.JTextField txtnombre;
    public javax.swing.JTextField txtnombre1;
    public javax.swing.JTextField txtruc;
    public javax.swing.JTextField txtruc1;
    public javax.swing.JTextField txttelefono;
    public javax.swing.JTextField txttelefono1;
    // End of variables declaration//GEN-END:variables
}
