/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package referenciales;

import conexion.conexion;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matrix
 */
public class timbrado extends javax.swing.JFrame {

    String accion = "";
    conexion bd = new conexion();
    SimpleDateFormat fec = new SimpleDateFormat("dd/MM/yyyy"); //formato para fecha

    public timbrado() {
        initComponents();
        bd.conecta();
        cargar_tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtcodigo = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtfecha2 = new javax.swing.JTextField();
        txtfecha1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtultimo = new javax.swing.JTextField();
        txtinicio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtactual = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnuevo = new javax.swing.JButton();
        btmodificar = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        btguardar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jcMousePanel2 = new jcMousePanel.jcMousePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mant. y Seguridad");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)), "Detalle"));
        jPanel1.setLayout(null);

        txtcodigo.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtcodigo.setForeground(new java.awt.Color(0, 153, 204));
        txtcodigo.setEnabled(false);
        jPanel1.add(txtcodigo);
        txtcodigo.setBounds(140, 20, 60, 30);

        txtdescripcion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtdescripcion.setForeground(new java.awt.Color(0, 153, 204));
        txtdescripcion.setEnabled(false);
        txtdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdescripcionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdescripcionKeyReleased(evt);
            }
        });
        jPanel1.add(txtdescripcion);
        txtdescripcion.setBounds(140, 70, 140, 30);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/timbrado.png"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);
        jcMousePanel1.setLayout(null);
        jPanel1.add(jcMousePanel1);
        jcMousePanel1.setBounds(30, 180, 540, 130);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Codigo:");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel9.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 20, 100, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Fecha Vencimiento:");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel11.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(260, 20, 130, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Timbrado:");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel12.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 70, 100, 20);

        txtfecha2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtfecha2.setForeground(new java.awt.Color(0, 153, 204));
        txtfecha2.setEnabled(false);
        txtfecha2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfecha2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfecha2KeyReleased(evt);
            }
        });
        jPanel1.add(txtfecha2);
        txtfecha2.setBounds(430, 20, 140, 30);

        txtfecha1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtfecha1.setForeground(new java.awt.Color(0, 153, 204));
        txtfecha1.setEnabled(false);
        txtfecha1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfecha1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfecha1KeyReleased(evt);
            }
        });
        jPanel1.add(txtfecha1);
        txtfecha1.setBounds(140, 120, 140, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Fecha Inicio:");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel13.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 120, 100, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Ultimo:");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel14.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel14);
        jLabel14.setBounds(290, 120, 100, 20);

        txtultimo.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtultimo.setForeground(new java.awt.Color(0, 153, 204));
        txtultimo.setEnabled(false);
        txtultimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtultimoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtultimoKeyReleased(evt);
            }
        });
        jPanel1.add(txtultimo);
        txtultimo.setBounds(430, 120, 140, 30);

        txtinicio.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtinicio.setForeground(new java.awt.Color(0, 153, 204));
        txtinicio.setEnabled(false);
        txtinicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtinicioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtinicioKeyReleased(evt);
            }
        });
        jPanel1.add(txtinicio);
        txtinicio.setBounds(430, 70, 140, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 204));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Inicio:");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel15.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel15);
        jLabel15.setBounds(290, 70, 100, 15);
        jPanel1.add(txtactual);
        txtactual.setBounds(660, 40, 6, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 270, 590, 330);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)), "......"));
        jPanel2.setLayout(null);

        btnuevo.setBackground(new java.awt.Color(0, 153, 153));
        btnuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnuevo.setForeground(new java.awt.Color(0, 102, 153));
        btnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/nuevo.png"))); // NOI18N
        btnuevo.setText("Nuevo");
        btnuevo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnuevo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnuevo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnuevo);
        btnuevo.setBounds(10, 90, 130, 40);

        btmodificar.setBackground(new java.awt.Color(0, 153, 153));
        btmodificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btmodificar.setForeground(new java.awt.Color(0, 102, 153));
        btmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/editar.png"))); // NOI18N
        btmodificar.setText("Modificar");
        btmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btmodificar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btmodificar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificarActionPerformed(evt);
            }
        });
        jPanel2.add(btmodificar);
        btmodificar.setBounds(10, 130, 130, 40);

        bteliminar.setBackground(new java.awt.Color(0, 153, 153));
        bteliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bteliminar.setForeground(new java.awt.Color(0, 102, 153));
        bteliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/borrar.png"))); // NOI18N
        bteliminar.setText("Eliminar");
        bteliminar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        bteliminar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bteliminar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });
        jPanel2.add(bteliminar);
        bteliminar.setBounds(10, 170, 130, 40);

        btguardar.setBackground(new java.awt.Color(0, 153, 153));
        btguardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btguardar.setForeground(new java.awt.Color(0, 102, 153));
        btguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/Save.png"))); // NOI18N
        btguardar.setText("Guardar");
        btguardar.setEnabled(false);
        btguardar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btguardar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btguardar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarActionPerformed(evt);
            }
        });
        jPanel2.add(btguardar);
        btguardar.setBounds(10, 210, 130, 40);

        btcancelar.setBackground(new java.awt.Color(0, 153, 153));
        btcancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btcancelar.setForeground(new java.awt.Color(0, 102, 153));
        btcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/cancelar.png"))); // NOI18N
        btcancelar.setText("Cancelar");
        btcancelar.setEnabled(false);
        btcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btcancelar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btcancelar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btcancelar);
        btcancelar.setBounds(10, 250, 130, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(610, 270, 160, 330);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Timbrado", "Fecha-Inicio", "Fecha-Vencimiento", "Inicio", "Ultimo", "Actual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setGridColor(new java.awt.Color(255, 255, 255));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMousePressed(evt);
            }
        });
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 750, 200);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Timbrados");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 40, 180, 20);

        txtbuscar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtbuscar.setForeground(new java.awt.Color(0, 153, 204));
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtbuscar);
        txtbuscar.setBounds(410, 40, 360, 30);

        jcMousePanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo.jpg"))); // NOI18N
        jcMousePanel2.setVisibleLogo(false);

        javax.swing.GroupLayout jcMousePanel2Layout = new javax.swing.GroupLayout(jcMousePanel2);
        jcMousePanel2.setLayout(jcMousePanel2Layout);
        jcMousePanel2Layout.setHorizontalGroup(
            jcMousePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jcMousePanel2Layout.setVerticalGroup(
            jcMousePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        getContentPane().add(jcMousePanel2);
        jcMousePanel2.setBounds(-50, -60, 840, 750);

        setSize(new java.awt.Dimension(802, 653));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtdescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescripcionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtfecha1.setEnabled(true);
            txtfecha1.requestFocus();
        }
    }//GEN-LAST:event_txtdescripcionKeyPressed

    private void txtdescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescripcionKeyReleased
        txtdescripcion.setText(txtdescripcion.getText().toUpperCase());
    }//GEN-LAST:event_txtdescripcionKeyReleased

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
        accion = "nuevo";
        btcancelar.doClick();
        btcancelar.setEnabled(true);
        bd.autonumerico("timbrado", "id_timbrado", txtcodigo);
        limpiar_campos1();
        txtdescripcion.setEnabled(true);
        txtdescripcion.requestFocus();
        bd.deshabilitar_botones(btnuevo, btmodificar, bteliminar, btguardar);
    }//GEN-LAST:event_btnuevoActionPerformed

    private void btmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificarActionPerformed
        if (txtcodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro", "Informe", JOptionPane.INFORMATION_MESSAGE);
        } else {
            accion = "modificar";
            btcancelar.setEnabled(true);
            bd.deshabilitar_botones(btnuevo, btmodificar, bteliminar, btguardar);
            habilitar_campos();
            txtdescripcion.requestFocus();

        }
    }//GEN-LAST:event_btmodificarActionPerformed

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
        if (txtcodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro", "Informe", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int mensaje = JOptionPane.showConfirmDialog(null, "Desea eliminar el registro", "Informe", JOptionPane.YES_NO_OPTION);
            if (mensaje == JOptionPane.YES_OPTION) {
                try {
                    String sql = "delete from timbrado where id_timbrado=?";
                    PreparedStatement eli = bd.conexion.prepareStatement(sql);
                    eli.setInt(1, Integer.parseInt(txtcodigo.getText()));
                    eli.execute();

                    cargar_tabla();
                    limpiar_campos();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al eliminar la tabla" + e);
                }
            }

        }
    }//GEN-LAST:event_bteliminarActionPerformed

    private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarActionPerformed
        if (txtdescripcion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe Ingresar Datos", "Informe", JOptionPane.INFORMATION_MESSAGE);
            txtdescripcion.setEnabled(true);
            txtdescripcion.requestFocus();
            return;
        }
        if (txtfecha1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe Ingresar Datos", "Informe", JOptionPane.INFORMATION_MESSAGE);
            txtfecha1.setEnabled(true);
            txtfecha1.requestFocus();
            return;
        }
        if (txtinicio.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe Ingresar Datos", "Informe", JOptionPane.INFORMATION_MESSAGE);
            txtinicio.setEnabled(true);
            txtinicio.requestFocus();
            return;
        }
        if (txtfecha2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe Ingresar Datos", "Informe", JOptionPane.INFORMATION_MESSAGE);
            txtfecha2.setEnabled(true);
            txtfecha2.requestFocus();
            return;
        }
        if (txtultimo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe Ingresar Datos", "Informe", JOptionPane.INFORMATION_MESSAGE);
            txtultimo.setEnabled(true);
            txtultimo.requestFocus();
            return;
        }

        grabar();
    }//GEN-LAST:event_btguardarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        accion = "";
        btcancelar.setEnabled(false);
        bd.habilitar_botones(btnuevo, btmodificar, bteliminar, btguardar);
        limpiar_campos();
        deshabilitar_campos();
        txtbuscar.requestFocus();
    }//GEN-LAST:event_btcancelarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        if (accion.equals("")) {
            String vid = tabla.getValueAt(tabla.getSelectedRow(), 0).toString();
            txtcodigo.setText(vid);
            recuperar_datos();

        }
    }//GEN-LAST:event_tablaMouseClicked

    private void tablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMousePressed
        if (accion.equals("")) {
            String vid = tabla.getValueAt(tabla.getSelectedRow(), 0).toString();
            txtcodigo.setText(vid);
            recuperar_datos();

        }
    }//GEN-LAST:event_tablaMousePressed

    private void tablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyPressed
        if (accion.equals("")) {
            String vid = tabla.getValueAt(tabla.getSelectedRow(), 0).toString();
            txtcodigo.setText(vid);
            recuperar_datos();

        }
    }//GEN-LAST:event_tablaKeyPressed

    private void tablaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyReleased
        if (accion.equals("")) {
            String vid = tabla.getValueAt(tabla.getSelectedRow(), 0).toString();
            txtcodigo.setText(vid);
            recuperar_datos();

        }
    }//GEN-LAST:event_tablaKeyReleased

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (tabla.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No existe ningun registro");
                txtbuscar.setText("");
                cargar_tabla();
                txtbuscar.requestFocus();
            } else {
                tabla.getSelectionModel().setSelectionInterval(0, 0);
                tabla.requestFocus();

            }
        }
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        cargar_tabla();
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void txtfecha2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfecha2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtinicio.setEnabled(true);
            txtinicio.requestFocus();
        }
    }//GEN-LAST:event_txtfecha2KeyPressed

    private void txtfecha2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfecha2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfecha2KeyReleased

    private void txtfecha1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfecha1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtfecha2.setEnabled(true);
            txtfecha2.requestFocus();
        }
    }//GEN-LAST:event_txtfecha1KeyPressed

    private void txtfecha1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfecha1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfecha1KeyReleased

    private void txtultimoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtultimoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btguardar.doClick();
        }
    }//GEN-LAST:event_txtultimoKeyPressed

    private void txtultimoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtultimoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtultimoKeyReleased

    private void txtinicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinicioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtultimo.setEnabled(true);
            txtultimo.requestFocus();
        }
    }//GEN-LAST:event_txtinicioKeyPressed

    private void txtinicioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinicioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinicioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timbrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timbrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timbrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timbrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timbrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btcancelar;
    public javax.swing.JButton bteliminar;
    public javax.swing.JButton btguardar;
    public javax.swing.JButton btmodificar;
    public javax.swing.JButton btnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private jcMousePanel.jcMousePanel jcMousePanel2;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtactual;
    private javax.swing.JTextField txtbuscar;
    public javax.swing.JTextField txtcodigo;
    public javax.swing.JTextField txtdescripcion;
    public javax.swing.JTextField txtfecha1;
    public javax.swing.JTextField txtfecha2;
    public javax.swing.JTextField txtinicio;
    public javax.swing.JTextField txtultimo;
    // End of variables declaration//GEN-END:variables

    private void cargar_tabla() {
        DefaultTableModel tab = (DefaultTableModel) tabla.getModel();
        tab.setRowCount(0);
        try {
            // ilike busca las letras por mayusculas y minisculas
            bd.listar_datos("SELECT id_timbrado, tim_numero, tim_fechainicio, tim_fechavencimiento, \n"
                    + "       inicio, ultimo, actual\n"
                    + "  FROM timbrado where id_timbrado::text like'%" + txtbuscar.getText() + "%' or tim_numero ilike '%" + txtbuscar.getText() + "%';");
            while (bd.resultado.next()) {
                tab.addRow(new Object[]{bd.resultado.getString("id_timbrado"),
                    bd.resultado.getString("tim_numero"),
                    bd.resultado.getString("tim_fechainicio"),
                    bd.resultado.getString("tim_fechavencimiento"),
                    bd.resultado.getString("inicio"),
                    bd.resultado.getString("ultimo"),
                    bd.resultado.getString("actual")
                });

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar la tabla" + e);
        }
    }

    private void limpiar_campos1() {
        txtdescripcion.setText("");
        txtfecha1.setText("");
        txtfecha2.setText("");
        txtinicio.setText("");
        txtultimo.setText("");
    }

    private void limpiar_campos() {
        txtcodigo.setText("");
        txtdescripcion.setText("");
        txtfecha1.setText("");
        txtfecha2.setText("");
        txtinicio.setText("");
        txtultimo.setText("");
    }

    private void deshabilitar_campos() {
        txtdescripcion.setEnabled(false);
        txtfecha1.setEnabled(false);
        txtfecha2.setEnabled(false);
        txtinicio.setEnabled(false);
        txtultimo.setEnabled(false);
    }

    private void habilitar_campos() {
        txtdescripcion.setEnabled(true);

    }

    private void grabar() {
        if (accion.equals("nuevo")) {
            //guardar
            try {
                String sql = "INSERT INTO timbrado(\n"
                        + "            id_timbrado, tim_numero, tim_fechainicio, tim_fechavencimiento, \n"
                        + "            inicio, ultimo, actual)\n"
                        + "    VALUES (?, ?,?, ?, \n"
                        + "            ?, ?, ?);";
                PreparedStatement p = bd.conexion.prepareStatement(sql);
                p.setInt(1, Integer.parseInt(txtcodigo.getText()));
                p.setString(2, txtdescripcion.getText());
                p.setDate(3, java.sql.Date.valueOf(convertir_fecha(txtfecha1.getText())));
                p.setDate(4, java.sql.Date.valueOf(convertir_fecha(txtfecha2.getText())));
                p.setString(5, txtinicio.getText());
                p.setString(6, txtultimo.getText());
                p.setInt(7, Integer.parseInt(txtinicio.getText()));
                p.execute();
                cargar_tabla();
                btcancelar.doClick();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al guardar los datos" + e);
            }

        } else {
            //modificar
            try {

                bd.retornar_ultimo("timbrado", "actual", txtactual);
                String sql = "UPDATE timbrado\n"
                        + "   SET  tim_numero=?, tim_fechainicio=?, tim_fechavencimiento=?, \n"
                        + "       inicio=?, ultimo=?, actual=?\n"
                        + " WHERE id_timbrado=?;";
                PreparedStatement p = bd.conexion.prepareStatement(sql);
                p.setInt(7, Integer.parseInt(txtcodigo.getText()));
                p.setString(1, txtdescripcion.getText());
                p.setDate(2, java.sql.Date.valueOf(convertir_fecha(txtfecha1.getText())));
                p.setDate(3, java.sql.Date.valueOf(convertir_fecha(txtfecha2.getText())));
                p.setString(4, txtinicio.getText());
                p.setString(5, txtultimo.getText());
                p.setInt(6, Integer.parseInt(txtactual.getText()));
                p.execute();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al modificar el registro" + e);
            }

            cargar_tabla();
            btcancelar.doClick();

        }

    }

    private String convertir_fecha(String fecha) {
        // 25-08-2016
        String dia = "", mes = "", anho = "";

        dia = fecha.substring(0, 2);
        mes = fecha.substring(3, 5);
        anho = fecha.substring(6, 10);
        fecha = anho + "-" + mes + "-" + dia;

        return fecha;
    }

    private void recuperar_datos() {
        try {
            bd.listar_datos("SELECT id_timbrado, tim_numero, tim_fechainicio, tim_fechavencimiento, \n"
                    + "       inicio, ultimo, actual\n"
                    + "  FROM timbrado where id_timbrado=" + txtcodigo.getText() + ";");
            if (bd.resultado.next()) {
                txtdescripcion.setText(bd.resultado.getString("tim_numero"));
                txtfecha1.setText(fec.format(bd.resultado.getDate("tim_fechainicio")));
                txtfecha2.setText(fec.format(bd.resultado.getDate("tim_fechavencimiento")));
                txtinicio.setText(bd.resultado.getString("inicio"));
                txtultimo.setText(bd.resultado.getString("ultimo"));

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al recuperar la tabla" + e);
        }
    }
}
