/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movimiento_ventas;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import conexion.conexion;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import menu.menu_principal;
import static movimiento_ventas.Ventas.txtfecha;

/**
 *
 * @author Matrix
 */
public class apertura extends javax.swing.JFrame {

    String accion = "";
    conexion bd = new conexion();
    SimpleDateFormat fec = new SimpleDateFormat("dd/MM/yyyy"); //formato para fecha
    DecimalFormat formateador = new DecimalFormat("#,##0"); //formato para separador de miles

    public apertura() {
        initComponents();
        bd.conecta();
        cargar_tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel2 = new jcMousePanel.jcMousePanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtcodigo = new javax.swing.JTextField();
        txtmonto = new javax.swing.JTextField();
        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtmontocheuqe = new javax.swing.JTextField();
        txtmontoguaranies = new javax.swing.JTextField();
        txtmontotarjeta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaarqueo = new javax.swing.JTable();
        txtsuma = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtsumacheque = new javax.swing.JTextField();
        txtsumatarjeta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtultimo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnuevo = new javax.swing.JButton();
        btmodificar = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        btguardar = new javax.swing.JButton();
        jcMousePanel3 = new jcMousePanel.jcMousePanel();
        jLabel1 = new javax.swing.JLabel();

        jcMousePanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Apertura de Caja::.");
        setResizable(false);
        getContentPane().setLayout(null);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Monto", "Estado", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setGridColor(new java.awt.Color(255, 255, 255));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMousePressed(evt);
            }
        });
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 40, 670, 200);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)), "Detalle"));
        jPanel1.setLayout(null);

        txtcodigo.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtcodigo.setForeground(new java.awt.Color(0, 153, 204));
        txtcodigo.setEnabled(false);
        jPanel1.add(txtcodigo);
        txtcodigo.setBounds(140, 20, 90, 30);

        txtmonto.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtmonto.setForeground(new java.awt.Color(0, 153, 204));
        txtmonto.setText("0");
        txtmonto.setEnabled(false);
        txtmonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmontoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmontoKeyReleased(evt);
            }
        });
        jPanel1.add(txtmonto);
        txtmonto.setBounds(140, 60, 240, 30);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/apertura.jpg"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);
        jcMousePanel1.setLayout(null);
        jPanel1.add(jcMousePanel1);
        jcMousePanel1.setBounds(30, 150, 350, 110);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Codigo:");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel9.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 20, 100, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("fecha:");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel11.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 110, 100, 20);

        txtfecha.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtfecha.setForeground(new java.awt.Color(0, 153, 204));
        txtfecha.setEnabled(false);
        jPanel1.add(txtfecha);
        txtfecha.setBounds(140, 110, 120, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Recaudaciones a depositar");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel12.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(320, 280, 210, 20);

        txtmontocheuqe.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtmontocheuqe.setForeground(new java.awt.Color(0, 153, 204));
        txtmontocheuqe.setText("0");
        txtmontocheuqe.setEnabled(false);
        txtmontocheuqe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmontocheuqeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmontocheuqeKeyReleased(evt);
            }
        });
        jPanel1.add(txtmontocheuqe);
        txtmontocheuqe.setBounds(470, 160, 150, 30);

        txtmontoguaranies.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtmontoguaranies.setForeground(new java.awt.Color(0, 153, 204));
        txtmontoguaranies.setText("0");
        txtmontoguaranies.setEnabled(false);
        txtmontoguaranies.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmontoguaraniesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmontoguaraniesKeyReleased(evt);
            }
        });
        jPanel1.add(txtmontoguaranies);
        txtmontoguaranies.setBounds(470, 40, 150, 30);

        txtmontotarjeta.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtmontotarjeta.setForeground(new java.awt.Color(0, 153, 204));
        txtmontotarjeta.setText("0");
        txtmontotarjeta.setEnabled(false);
        txtmontotarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmontotarjetaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmontotarjetaKeyReleased(evt);
            }
        });
        jPanel1.add(txtmontotarjeta);
        txtmontotarjeta.setBounds(470, 100, 150, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Monto:");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel13.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 60, 100, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Monto Guaranies:");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel14.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel14);
        jLabel14.setBounds(480, 10, 130, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 204));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Monto Tarjeta:");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel15.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel15);
        jLabel15.setBounds(480, 70, 130, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(370, 330, 250, 110);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Monto Cheque:");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel16.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel16);
        jLabel16.setBounds(480, 130, 130, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Arqueo");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel17.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 290, 130, 20);

        tablaarqueo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "factura", "tipo", "banco", "nroboleta", "monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaarqueo);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(50, 320, 290, 120);

        txtsuma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsumaKeyReleased(evt);
            }
        });
        jPanel1.add(txtsuma);
        txtsuma.setBounds(180, 300, 160, 20);

        jLabel2.setText("suma tarjeta");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 480, 100, 14);
        jPanel1.add(txtsumacheque);
        txtsumacheque.setBounds(20, 450, 160, 20);
        jPanel1.add(txtsumatarjeta);
        txtsumatarjeta.setBounds(190, 450, 160, 20);

        jLabel3.setText("Suma guaranies");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 280, 100, 14);

        jLabel4.setText("suma cheque");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 484, 100, 10);
        jPanel1.add(txtultimo);
        txtultimo.setBounds(720, 60, 6, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 240, 670, 270);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)), "......"));
        jPanel2.setLayout(null);

        btnuevo.setBackground(new java.awt.Color(0, 153, 153));
        btnuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnuevo.setForeground(new java.awt.Color(0, 102, 153));
        btnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/nuevo.png"))); // NOI18N
        btnuevo.setText("Apertura");
        btnuevo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnuevo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnuevo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnuevo);
        btnuevo.setBounds(10, 190, 130, 40);

        btmodificar.setBackground(new java.awt.Color(0, 153, 153));
        btmodificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btmodificar.setForeground(new java.awt.Color(0, 102, 153));
        btmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/editar.png"))); // NOI18N
        btmodificar.setText("Cierre");
        btmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btmodificar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btmodificar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificarActionPerformed(evt);
            }
        });
        jPanel2.add(btmodificar);
        btmodificar.setBounds(10, 230, 130, 40);

        bteliminar.setBackground(new java.awt.Color(0, 153, 153));
        bteliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bteliminar.setForeground(new java.awt.Color(0, 102, 153));
        bteliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/borrar.png"))); // NOI18N
        bteliminar.setText("Eliminar");
        bteliminar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        bteliminar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bteliminar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });
        jPanel2.add(bteliminar);
        bteliminar.setBounds(230, 100, 130, 40);

        btcancelar.setBackground(new java.awt.Color(0, 153, 153));
        btcancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btcancelar.setForeground(new java.awt.Color(0, 102, 153));
        btcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/cancelar.png"))); // NOI18N
        btcancelar.setText("Cancelar");
        btcancelar.setEnabled(false);
        btcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btcancelar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btcancelar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btcancelar);
        btcancelar.setBounds(10, 310, 130, 40);

        btguardar.setBackground(new java.awt.Color(0, 153, 153));
        btguardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btguardar.setForeground(new java.awt.Color(0, 102, 153));
        btguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/Save.png"))); // NOI18N
        btguardar.setText("Confirmar");
        btguardar.setEnabled(false);
        btguardar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btguardar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btguardar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarActionPerformed(evt);
            }
        });
        jPanel2.add(btguardar);
        btguardar.setBounds(10, 270, 130, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(720, 40, 160, 470);

        jcMousePanel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo.jpg"))); // NOI18N
        jcMousePanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Apertura y Cierre de Caja");
        jcMousePanel3.add(jLabel1);
        jLabel1.setBounds(440, 80, 330, 20);

        getContentPane().add(jcMousePanel3);
        jcMousePanel3.setBounds(-80, -70, 970, 600);

        setSize(new java.awt.Dimension(902, 568));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
//        if (accion.equals("")) {
//            String vid = tabla.getValueAt(tabla.getSelectedRow(), 0).toString();
//            txtcodigo.setText(vid);
//            recuperar_datos();
//
//        }
    }//GEN-LAST:event_tablaMouseClicked

    private void tablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMousePressed
        if (accion.equals("")) {
            String vid = tabla.getValueAt(tabla.getSelectedRow(), 0).toString();
            txtcodigo.setText(vid);
            recuperar_datos();

        }
    }//GEN-LAST:event_tablaMousePressed

    private void tablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyPressed
        if (accion.equals("")) {
            String vid = tabla.getValueAt(tabla.getSelectedRow(), 0).toString();
            txtcodigo.setText(vid);
            recuperar_datos();

        }
    }//GEN-LAST:event_tablaKeyPressed

    private void tablaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyReleased
        if (accion.equals("")) {
            String vid = tabla.getValueAt(tabla.getSelectedRow(), 0).toString();
            txtcodigo.setText(vid);
            recuperar_datos();

        }
    }//GEN-LAST:event_tablaKeyReleased

    private void txtmontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btguardar.doClick();
        }
    }//GEN-LAST:event_txtmontoKeyPressed

    private void txtmontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontoKeyReleased
        txtmonto.setText(txtmonto.getText().toUpperCase());
    }//GEN-LAST:event_txtmontoKeyReleased

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
        accion = "nuevo";
        bd.autonumerico("apertura_cierre", "id_apertura", txtcodigo);
        txtfecha.setText(fec.format(new Date()));
        accion = "nuevo";
        btcancelar.doClick();
        btcancelar.setEnabled(true);
        txtmonto.setEnabled(true);
        txtmonto.requestFocus();
        bd.deshabilitar_botones(btnuevo, btmodificar, bteliminar, btguardar);
    }//GEN-LAST:event_btnuevoActionPerformed

    private void btmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificarActionPerformed
        if (txtcodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro", "Informe", JOptionPane.INFORMATION_MESSAGE);
        } else {
            accion = "modificar";
            recuperar_cobro();
            btcancelar.setEnabled(true);
            bd.deshabilitar_botones(btnuevo, btmodificar, bteliminar, btguardar);
//            habilitar_campos();
//            txtmonto.requestFocus();

        }


    }//GEN-LAST:event_btmodificarActionPerformed

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
//        if (txtcodigo.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Seleccione un registro", "Informe", JOptionPane.INFORMATION_MESSAGE);
//        } else {
//            int mensaje = JOptionPane.showConfirmDialog(null, "Desea eliminar el registro", "Informe", JOptionPane.YES_NO_OPTION);
//            if (mensaje == JOptionPane.YES_OPTION) {
//                try {
//                    String sql = "delete from marca where id_marca=?";
//                    PreparedStatement eli = bd.conexion.prepareStatement(sql);
//                    eli.setInt(1, Integer.parseInt(txtcodigo.getText()));
//                    eli.execute();
//
//                    cargar_tabla();
//                    limpiar_campos();
//
//                } catch (Exception e) {
//                    JOptionPane.showMessageDialog(null, "Error al eliminar la tabla" + e);
//                }
//            }
//
//        }
    }//GEN-LAST:event_bteliminarActionPerformed

    private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarActionPerformed
        if (txtmonto.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe Ingresar Monto", "Informe", JOptionPane.INFORMATION_MESSAGE);
            txtmonto.requestFocus();
            return;
        }

        grabar();
    }//GEN-LAST:event_btguardarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        accion = "";
        btcancelar.setEnabled(false);
        bd.habilitar_botones(btnuevo, btmodificar, bteliminar, btguardar);
        txtcodigo.setText("");
        txtmonto.setText("");
        txtfecha.setText("");
        txtmonto.setEnabled(false);
        txtmontoguaranies.setText("0");
        txtmontocheuqe.setText("0");
        txtmontotarjeta.setText("0");
    }//GEN-LAST:event_btcancelarActionPerformed

    private void txtmontocheuqeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontocheuqeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmontocheuqeKeyPressed

    private void txtmontocheuqeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontocheuqeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmontocheuqeKeyReleased

    private void txtmontoguaraniesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontoguaraniesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmontoguaraniesKeyPressed

    private void txtmontoguaraniesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontoguaraniesKeyReleased

    }//GEN-LAST:event_txtmontoguaraniesKeyReleased

    private void txtmontotarjetaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontotarjetaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmontotarjetaKeyPressed

    private void txtmontotarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontotarjetaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmontotarjetaKeyReleased

    private void txtsumaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsumaKeyReleased

    }//GEN-LAST:event_txtsumaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(apertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(apertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(apertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(apertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new apertura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btcancelar;
    public javax.swing.JButton bteliminar;
    public javax.swing.JButton btguardar;
    public javax.swing.JButton btmodificar;
    public javax.swing.JButton btnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private jcMousePanel.jcMousePanel jcMousePanel2;
    private jcMousePanel.jcMousePanel jcMousePanel3;
    private javax.swing.JTable tabla;
    public static javax.swing.JTable tablaarqueo;
    public javax.swing.JTextField txtcodigo;
    public javax.swing.JTextField txtfecha;
    public javax.swing.JTextField txtmonto;
    public javax.swing.JTextField txtmontocheuqe;
    public javax.swing.JTextField txtmontoguaranies;
    public javax.swing.JTextField txtmontotarjeta;
    private javax.swing.JTextField txtsuma;
    private javax.swing.JTextField txtsumacheque;
    private javax.swing.JTextField txtsumatarjeta;
    private javax.swing.JTextField txtultimo;
    // End of variables declaration//GEN-END:variables

    private void cargar_tabla() {
        DefaultTableModel tab = (DefaultTableModel) tabla.getModel();
        tab.setRowCount(0);
        try {
            // ilike busca las letras por mayusculas y minisculas
            bd.listar_datos("SELECT a.id_apertura, a.aper_fecha, a.aper_monto, a.id_estado,  e.est_descri as estado\n"
                    + "  FROM apertura_cierre a inner join estado e on e.id_estado = a.id_estado where a.id_estado = 1 ;");
            while (bd.resultado.next()) {
                tab.addRow(new Object[]{bd.resultado.getString("id_apertura"),
                    bd.resultado.getString("aper_monto"),
                    bd.resultado.getString("estado"),
                    bd.resultado.getString("aper_fecha")});

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar la tabla" + e);
        }
    }

    private void grabar() {
        if (accion.equals("nuevo")) {
            //guardar
            try {
                String sql = "INSERT INTO apertura_cierre(id_apertura, id_caja, id_usuario, aper_fecha, aper_monto, cierre_fecha, \n"
                        + "            cierre_montocheque, cierre_montotarjeta, cierre_montoefectivo,id_estado)\n"
                        + "    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
                PreparedStatement p = bd.conexion.prepareStatement(sql);
                p.setInt(1, Integer.parseInt(txtcodigo.getText()));
                p.setInt(2, 1);
                p.setInt(3, 1);
                p.setDate(4, java.sql.Date.valueOf(convertir_fecha(txtfecha.getText())));
                p.setString(5, txtmonto.getText());
                p.setDate(6, java.sql.Date.valueOf(convertir_fecha(txtfecha.getText())));
                p.setInt(7, 0);
                p.setInt(8, 0);
                p.setInt(9, 0);
                p.setInt(10, 1);

                p.execute();
                cargar_tabla();
                btcancelar.doClick();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al guardar los datos" + e);
            }
            try {
                bd.retornar_ultimo("apertura_cierre", "id_apertura", txtultimo);
               
                menu_principal.txtidapertura.setText(txtultimo.getText());
                dispose();
            } catch (Exception e) {
                System.out.println("error al recuperar datos"+e);
            }

        } else {
            //modificar
            try {
                String sql = "UPDATE apertura_cierre\n"
                        + "   SET  id_caja=?, id_usuario=?, aper_fecha=?, aper_monto=?, \n"
                        + "       cierre_fecha=?, cierre_montocheque=?, cierre_montotarjeta=?, \n"
                        + "       cierre_montoefectivo=?, id_estado=?\n"
                        + " WHERE id_apertura=?;";
                PreparedStatement p = bd.conexion.prepareStatement(sql);
                p.setInt(10, Integer.parseInt(txtcodigo.getText()));
                p.setInt(1, 1);
                p.setInt(2, 1);
                p.setDate(3, java.sql.Date.valueOf(convertir_fecha(txtfecha.getText())));
                p.setString(4, txtmonto.getText());
                p.setDate(5, java.sql.Date.valueOf(convertir_fecha(txtfecha.getText())));
                p.setString(6, txtmontocheuqe.getText());
                p.setString(7, txtmontotarjeta.getText());
                p.setString(8, txtmontoguaranies.getText());
                p.setInt(9, 2);
                p.execute();

                //eliminamos los detalles de cobro del dia
                String sql3 = "DELETE FROM detalle_tipocobro;";
                PreparedStatement eli = bd.conexion.prepareStatement(sql3);
                eli.execute();

                //arqueo
                int vidarqueo = 0;
                bd.listar_datos("select nextval('idarqueo')as codigo");
                bd.resultado.next();
                vidarqueo = bd.resultado.getInt("codigo");

                String sqlarqueo = "INSERT INTO arqueo(\n"
                        + "            id_arqueo, arq_fecha, id_apertura, arq_montotarjeta, arq_montochque, \n"
                        + "            arq_montoefectivo)\n"
                        + "    VALUES (?, ?, ?, ?, ?, \n"
                        + "            ?);";
                PreparedStatement arq = bd.conexion.prepareStatement(sqlarqueo);
                arq.setInt(1, vidarqueo);
                arq.setDate(2, java.sql.Date.valueOf(convertir_fecha(txtfecha.getText())));
                arq.setInt(3, Integer.parseInt(txtcodigo.getText()));
                arq.setString(4, txtmontocheuqe.getText());
                arq.setString(5, txtmontotarjeta.getText());
                arq.setString(6, txtmontoguaranies.getText());
                arq.execute();

                // recaudaciones a depositar
                int vidrecau = 0;
                bd.listar_datos("select nextval('idrecaudaciones')as codigo");
                bd.resultado.next();
                vidrecau = bd.resultado.getInt("codigo");
                String sqlrecau = "INSERT INTO recaudaciones_adepositar(id_recaudaciones, recau_monto, id_estado, id_arqueo, recau_fecha, \n"
                        + "            recau_nroboleta, recau_ctabancaria)\n"
                        + "    VALUES (?, ?, ?, ?, ?, \n"
                        + "            ?, ?);";
                PreparedStatement precau = bd.conexion.prepareStatement(sqlrecau);
                precau.setInt(1, vidrecau);
                precau.setString(2, txtmontoguaranies.getText());
                precau.setInt(3, 1);
                precau.setInt(4, vidarqueo);
                precau.setDate(5, java.sql.Date.valueOf(convertir_fecha(txtfecha.getText())));
                precau.setString(6, "0");
                precau.setString(7, "00");
                precau.execute();

                cargar_tabla();
                btcancelar.doClick();

            } catch (Exception e) {
//                JOptionPane.showMessageDialog(null, "Error al modificar el registro" + e);
                System.out.println("error: " + e);
            }

                menu_principal.txtidapertura.setText("");
                dispose();

        }
    }

    private String convertir_fecha(String fecha) {
        // 25-08-2016
        String dia = "", mes = "", anho = "";

        dia = fecha.substring(0, 2);
        mes = fecha.substring(3, 5);
        anho = fecha.substring(6, 10);
        fecha = anho + "-" + mes + "-" + dia;

        return fecha;
    }

    private void recuperar_datos() {
        try {
            bd.listar_datos("SELECT id_apertura,  aper_fecha, aper_monto\n"
                    + "  FROM apertura_cierre where id_apertura=" + txtcodigo.getText() + ";");
            if (bd.resultado.next()) {
                txtmonto.setText(bd.resultado.getString("aper_monto"));
                txtfecha.setText(fec.format(bd.resultado.getDate("aper_fecha")));

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al recuperar la tabla" + e);
        }
    }

    private void habilitar_campos() {

    }

    private void recuperar_cobro() {
        DefaultTableModel tab = (DefaultTableModel) tablaarqueo.getModel();
        tab.setRowCount(0);
        try {
            // ilike busca las letras por mayusculas y minisculas
            bd.listar_datos("SELECT id_factura, id_tipo, id_banco, nro_boleta, det_monto\n"
                    + "  FROM detalle_tipocobro  ;");
            while (bd.resultado.next()) {
                tab.addRow(new Object[]{bd.resultado.getString("id_factura"),
                    bd.resultado.getString("id_tipo"),
                    bd.resultado.getString("id_banco"),
                    bd.resultado.getString("nro_boleta"),
                    bd.resultado.getString("det_monto")});
                suma();
                txtmontoguaranies.setText(txtsuma.getText());
                txtmontocheuqe.setText(txtsumacheque.getText());
                txtmontotarjeta.setText(txtsumatarjeta.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al recuperar cobro" + e);

        }
    }

    private void suma() {

        int vtotal = 0;
        int vtotal1 = 0;
        int vtotal2 = 0;
        for (int i = 0; i < tablaarqueo.getRowCount(); i++) {
            //Toma el monto de la columna sub total en la variable vtot
            int vtot = Integer.parseInt(tablaarqueo.getValueAt(i, 4).toString().replace(".", ""));
            int cod = Integer.parseInt(tablaarqueo.getValueAt(i, 1).toString());
            if (cod == 1) {
                vtotal += vtot;
                txtsuma.setText(formateador.format(vtotal));

            } else {

                if (cod == 2) {
                    vtotal1 += vtot;
                    txtsumacheque.setText(formateador.format(vtotal1));

                }

                if (cod == 3) {
                    vtotal2 += vtot;
                    txtsumatarjeta.setText(formateador.format(vtotal2));
                }
            }

        }

    }

}
