/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movimiento_ventas;

import conexion.conexion;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oscar
 */
public class Busqueda_Mercaderia extends javax.swing.JDialog {

    conexion bd = new conexion();

    public Busqueda_Mercaderia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bd.conecta();
        setTitle("Busqueda de Mercaderias");
        cargar_tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btok = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda de Mercaderias");
        setResizable(false);
        getContentPane().setLayout(null);

        tabla.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        tabla.setForeground(new java.awt.Color(24, 223, 101));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descripcion", "Precio Venta", "Impuesto", "Stock", "Deposito"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 490, 130);

        btok.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btok.setForeground(new java.awt.Color(88, 188, 127));
        btok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/ok.png"))); // NOI18N
        btok.setEnabled(false);
        btok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btokActionPerformed(evt);
            }
        });
        getContentPane().add(btok);
        btok.setBounds(190, 210, 100, 33);

        txtbuscar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtbuscar.setForeground(new java.awt.Color(36, 178, 168));
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtbuscar);
        txtbuscar.setBounds(200, 40, 300, 30);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(14, 202, 103));
        jLabel1.setText("Mercaderias");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 100, 20);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo.jpg"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);
        jcMousePanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/buscar.png"))); // NOI18N
        jcMousePanel1.add(jButton1);
        jButton1.setBounds(60, 40, 40, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 102));
        jLabel3.setText("Buscar");
        jcMousePanel1.add(jLabel3);
        jLabel3.setBounds(120, 50, 70, 15);

        getContentPane().add(jcMousePanel1);
        jcMousePanel1.setBounds(0, 0, 510, 280);

        setSize(new java.awt.Dimension(525, 314));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        txtbuscar.setText(txtbuscar.getText().toUpperCase());
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (tabla.getRowCount() == 0) {   //si la tabla no tiene ningun registro la fila esta en cero
                JOptionPane.showMessageDialog(null, "No existe Datos", "Informe", JOptionPane.INFORMATION_MESSAGE);
                txtbuscar.setText("");
                cargar_tabla();
                txtbuscar.requestFocus();
            } else {
                tabla.getSelectionModel().setSelectionInterval(0, 0);
                tabla.requestFocus();
            }
        }
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        cargar_tabla();
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void tablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btok.setEnabled(true);
            btok.doClick();
        }
    }//GEN-LAST:event_tablaKeyPressed

    private void btokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btokActionPerformed
        if (tabla.getRowCount() > 0) {  //si hay un registro
            String vcodigo = "", vdescripcion = "", vprecioc = "", vimpuesto = "", vstock = "",vdep="";
            int fila = tabla.getSelectedRow();
            vcodigo = tabla.getValueAt(fila, 0).toString();
            vdescripcion = tabla.getValueAt(fila, 1).toString();
            vprecioc = tabla.getValueAt(fila, 2).toString();
            vimpuesto = tabla.getValueAt(fila, 3).toString();
            vstock = tabla.getValueAt(fila, 4).toString();
            vdep= tabla.getValueAt(fila,5 ).toString();
            if (presupuest.bandera == 1) {
                //declara su propia variable 
                //mientras recorre se auto incremeta 
                for (int i = 0; i < presupuest.detalle.getRowCount(); i++) {

                    String vcod = presupuest.detalle.getValueAt(i, 0).toString();
                    if (vcod.equals(vcodigo)) {
                        JOptionPane.showMessageDialog(null, "El producto seleccionado ya existe en el detalle", "Error", JOptionPane.QUESTION_MESSAGE);
                        return;

                    }

                }
                presupuest.txtcodigo.setText(vcodigo);
                presupuest.txtdescripcion.setText(vdescripcion);
                presupuest.txtprecio.setText(vprecioc);
                presupuest.txtimpuesto.setText(vimpuesto);
                presupuest.txtcantidad.setEnabled(true);
                presupuest.txtcantidad.requestFocus();
                presupuest.txtstock.setText(vstock);
                
                dispose();    //cierra el formulario
            } else {

            }
            if (Ventas.bandera == 1) {
                //declara su propia variable 
                //mientras recorre se auto incremeta 
                for (int i = 0; i < Ventas.detalle.getRowCount(); i++) {

                    String vcod = Ventas.detalle.getValueAt(i, 0).toString();
                    if (vcod.equals(vcodigo)) {
                        JOptionPane.showMessageDialog(null, "El producto seleccionado ya existe en el detalle", "Error", JOptionPane.QUESTION_MESSAGE);
                        return;

                    }

                }

                Ventas.txtcodigo.setText(vcodigo);
                Ventas.txtdescripcion.setText(vdescripcion);
                Ventas.txtprecio.setText(vprecioc);
                Ventas.txtimpuesto.setText(vimpuesto);
                Ventas.txtcantidad.setEnabled(true);
                Ventas.txtcantidad.requestFocus();
                Ventas.txtstock.setText(vstock);
                Ventas.txtiddeposito.setText(vdep);
                dispose();    //cierra el formulario
            } else {

            }
        }
    }//GEN-LAST:event_btokActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        btok.setEnabled(true);
    }//GEN-LAST:event_tablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda_Mercaderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda_Mercaderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda_Mercaderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda_Mercaderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Busqueda_Mercaderia dialog = new Busqueda_Mercaderia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btok;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JTable tabla;
    public static javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables

    private void cargar_tabla() {

        DefaultTableModel tab = (DefaultTableModel) tabla.getModel();
        tab.setRowCount(0);
        DecimalFormat formato = new DecimalFormat("#,##0");
        try {
            // ilike busca las letras por mayusculas y minisculas
            bd.listar_datos("SELECT s.id_articulo as codigo,s.id_deposito as deposito,  s.stock_cant as cantidad, a.art_descri as descripcion,\n"
                    + "                    a.art_precioc as precio , a.id_impuesto as impuesto\n"
                    + "                     FROM stock s \n"
                    + "                    inner join articulos a on a.id_articulo= s.id_articulo\n"
                    + "                    inner join deposito d on d.id_deposito= s.id_deposito  where s.id_articulo ::text like'%" + txtbuscar.getText() + "%' or a.art_descri ilike '%" + txtbuscar.getText() + "%';");
            while (bd.resultado.next()) {
                tab.addRow(new Object[]{bd.resultado.getString("codigo"),
                    bd.resultado.getString("descripcion"),
                    formato.format(bd.resultado.getInt("precio")),
                    bd.resultado.getString("impuesto"),
                    bd.resultado.getString("cantidad"),
                    bd.resultado.getString("deposito")});

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar la tabla" + e);
        }
    }
}
