/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movimiento_ventas;

import conexion.conexion;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oscar
 */
public class Busqueda_Factura extends javax.swing.JDialog {

    conexion bd = new conexion();

    public Busqueda_Factura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bd.conecta();
        cargar_tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        btok = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Facturas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 7, 220, 20);

        tabla.setForeground(new java.awt.Color(34, 136, 225));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Fecha", "Cliente", "Monto", "Presupuesto Nº"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 590, 150);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo.jpg"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);
        jcMousePanel1.setLayout(null);

        btok.setForeground(new java.awt.Color(39, 161, 207));
        btok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/ok.png"))); // NOI18N
        btok.setEnabled(false);
        btok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btokActionPerformed(evt);
            }
        });
        jcMousePanel1.add(btok);
        btok.setBounds(260, 220, 90, 33);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/buscar.png"))); // NOI18N
        jcMousePanel1.add(jButton1);
        jButton1.setBounds(20, 30, 40, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 102));
        jLabel2.setText("Buscar");
        jcMousePanel1.add(jLabel2);
        jLabel2.setBounds(80, 40, 70, 15);

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        jcMousePanel1.add(txtbuscar);
        txtbuscar.setBounds(140, 40, 460, 20);

        getContentPane().add(jcMousePanel1);
        jcMousePanel1.setBounds(0, 0, 610, 280);

        setSize(new java.awt.Dimension(628, 316));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (tabla.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No existen datos");
                txtbuscar.setText("");
                cargar_tabla();
            } else {
                tabla.getSelectionModel().setSelectionInterval(0, 0);
                tabla.requestFocus();
            }
        }

    }//GEN-LAST:event_txtbuscarKeyPressed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        cargar_tabla(); //cuando suelto el teclado
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void tablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btok.setEnabled(true);
            btok.doClick();
        }
    }//GEN-LAST:event_tablaKeyPressed

    private void btokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btokActionPerformed
        String vcod = "";

        vcod = tabla.getValueAt(tabla.getSelectedRow(), 0).toString();      //seleccionamos la columna de la fila 0
        Ventas.txtn.setText(vcod);
        dispose();


    }//GEN-LAST:event_btokActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked

        btok.setEnabled(true);


    }//GEN-LAST:event_tablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda_Factura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda_Factura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda_Factura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda_Factura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Busqueda_Factura dialog = new Busqueda_Factura(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btok;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    public static javax.swing.JTable tabla;
    protected static javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables

    private void cargar_tabla() {
        DefaultTableModel tab = (DefaultTableModel) tabla.getModel();
        tab.setRowCount(0);
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/yyyy"); //visualiza la forma de fecha
        try {
            bd.listar_datos("SELECT id_factura,   id_cliente, id_presupuesto, fact_numero, fact_fecha, fact_monto, id_estado\n"
                    + "  FROM factura "
                    + " where id_estado=1 and(id_factura::text like '%" + txtbuscar.getText() + "%' or "
                    + " id_cliente::text like '%" + txtbuscar.getText() + "%' )order by id_factura");
            while (bd.resultado.next()) {
                tab.addRow(new Object[]{bd.resultado.getString("id_factura"),
                    formatofecha.format(bd.resultado.getDate("fact_fecha")),
                    bd.resultado.getString("id_cliente"),
                    bd.resultado.getString("fact_monto"),
                    bd.resultado.getString("id_presupuesto")
                });

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Error al Cargar tabla " + e,
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }
}
