/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movimiento_ventas;

import conexion.conexion;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import menu.menu_principal;

/**
 *
 * @author Matrix
 */
public class presupuest extends javax.swing.JFrame {

    conexion bd = new conexion();
    SimpleDateFormat fec = new SimpleDateFormat("dd/MM/yyyy"); //formato para fecha
    DecimalFormat formateador = new DecimalFormat("#,##0"); //formato para separador de miles
    String accion = "";
    //variable estatico para poder ver en otros formularios
    public static int bandera = 0;

    public presupuest() {
        initComponents();
        bd.conecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel2 = new jcMousePanel.jcMousePanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtn = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        btagregar = new javax.swing.JButton();
        btquitar = new javax.swing.JButton();
        txtimpuesto = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detalle = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtsub5 = new javax.swing.JTextField();
        txtiva5 = new javax.swing.JTextField();
        txtiva10 = new javax.swing.JTextField();
        txtexenta = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtsub10 = new javax.swing.JTextField();
        btnuevo = new javax.swing.JButton();
        btmodificar = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        btguardar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        jcMousePanel3 = new jcMousePanel.jcMousePanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtidcliente = new javax.swing.JTextField();
        txtcliente = new javax.swing.JTextField();
        txtruc = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtempleado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtidempleado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Presupuesto:.");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2)));
        jPanel3.setLayout(null);

        jLabel13.setForeground(new java.awt.Color(0, 102, 153));
        jLabel13.setText("N°");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(60, 80, 60, 20);

        txtn.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtn.setForeground(new java.awt.Color(0, 153, 204));
        txtn.setEnabled(false);
        txtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnActionPerformed(evt);
            }
        });
        txtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnKeyReleased(evt);
            }
        });
        jPanel3.add(txtn);
        txtn.setBounds(110, 80, 80, 19);

        jLabel14.setForeground(new java.awt.Color(0, 102, 153));
        jLabel14.setText("Fecha");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 40, 60, 20);

        txtfecha.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtfecha.setForeground(new java.awt.Color(0, 153, 204));
        txtfecha.setEnabled(false);
        jPanel3.add(txtfecha);
        txtfecha.setBounds(60, 40, 80, 19);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Presupuesto");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(140, 10, 190, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("EcoLuz Comercial");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(300, 0, 390, 60);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("De Julio Cesar Romero Lopez");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(370, 60, 210, 17);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 153));
        jLabel22.setText("Venta de Materiales Electricos");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(370, 80, 210, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Cerro Cora Nº 253 c/ Iturbe");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(370, 100, 200, 17);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(31, 0, 630, 140);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2)));
        jPanel4.setEnabled(false);
        jPanel4.setLayout(null);

        jLabel15.setForeground(new java.awt.Color(0, 102, 153));
        jLabel15.setText("Codigo");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(30, 10, 80, 14);

        jLabel16.setForeground(new java.awt.Color(0, 102, 153));
        jLabel16.setText("Descripcion");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(130, 10, 100, 14);

        jLabel17.setForeground(new java.awt.Color(0, 102, 153));
        jLabel17.setText("Precio");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(340, 10, 70, 14);

        jLabel18.setForeground(new java.awt.Color(0, 102, 153));
        jLabel18.setText("Cantidad");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(240, 10, 90, 14);

        txtcodigo.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtcodigo.setForeground(new java.awt.Color(0, 51, 204));
        txtcodigo.setEnabled(false);
        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoKeyTyped(evt);
            }
        });
        jPanel4.add(txtcodigo);
        txtcodigo.setBounds(20, 30, 60, 20);

        txtdescripcion.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtdescripcion.setForeground(new java.awt.Color(0, 51, 204));
        txtdescripcion.setEnabled(false);
        jPanel4.add(txtdescripcion);
        txtdescripcion.setBounds(110, 30, 100, 20);

        txtprecio.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtprecio.setForeground(new java.awt.Color(0, 51, 204));
        txtprecio.setEnabled(false);
        jPanel4.add(txtprecio);
        txtprecio.setBounds(320, 30, 70, 20);

        txtcantidad.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtcantidad.setForeground(new java.awt.Color(0, 51, 204));
        txtcantidad.setEnabled(false);
        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });
        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });
        jPanel4.add(txtcantidad);
        txtcantidad.setBounds(240, 30, 60, 20);

        btagregar.setText("Agregar");
        btagregar.setEnabled(false);
        btagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btagregarActionPerformed(evt);
            }
        });
        jPanel4.add(btagregar);
        btagregar.setBounds(170, 70, 71, 23);

        btquitar.setText("Quitar");
        btquitar.setEnabled(false);
        btquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btquitarActionPerformed(evt);
            }
        });
        jPanel4.add(btquitar);
        btquitar.setBounds(250, 70, 70, 23);

        txtimpuesto.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtimpuesto.setForeground(new java.awt.Color(0, 51, 204));
        txtimpuesto.setEnabled(false);
        jPanel4.add(txtimpuesto);
        txtimpuesto.setBounds(410, 30, 80, 20);

        jLabel24.setText("Impuestos");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(410, 90, 150, 14);

        detalle.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2)));
        detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Cantidad", "Precio", "5%", "10%", "Exenta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detalleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(detalle);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 550, 160);

        jLabel19.setForeground(new java.awt.Color(0, 102, 153));
        jLabel19.setText("Sub total");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(250, 290, 110, 14);

        jLabel20.setForeground(new java.awt.Color(0, 102, 153));
        jLabel20.setText("Total Impuesto");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(50, 280, 100, 14);

        jLabel21.setForeground(new java.awt.Color(0, 102, 153));
        jLabel21.setText("Total Presupuesto");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(250, 320, 120, 14);

        txtsub5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtsub5.setForeground(new java.awt.Color(0, 51, 204));
        txtsub5.setText("0");
        txtsub5.setEnabled(false);
        jPanel4.add(txtsub5);
        txtsub5.setBounds(330, 280, 60, 20);

        txtiva5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtiva5.setForeground(new java.awt.Color(0, 51, 204));
        txtiva5.setText("0");
        txtiva5.setEnabled(false);
        jPanel4.add(txtiva5);
        txtiva5.setBounds(30, 320, 60, 20);

        txtiva10.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtiva10.setForeground(new java.awt.Color(0, 51, 204));
        txtiva10.setText("0");
        txtiva10.setEnabled(false);
        jPanel4.add(txtiva10);
        txtiva10.setBounds(120, 320, 80, 20);

        txtexenta.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtexenta.setForeground(new java.awt.Color(0, 51, 204));
        txtexenta.setText("0");
        txtexenta.setEnabled(false);
        jPanel4.add(txtexenta);
        txtexenta.setBounds(500, 280, 60, 20);

        txttotal.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txttotal.setForeground(new java.awt.Color(0, 51, 204));
        txttotal.setText("0");
        txttotal.setEnabled(false);
        jPanel4.add(txttotal);
        txttotal.setBounds(390, 320, 140, 20);

        jLabel25.setText("5%");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(50, 300, 50, 14);

        jLabel26.setText("10%");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(140, 300, 60, 14);

        txtsub10.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtsub10.setForeground(new java.awt.Color(0, 51, 204));
        txtsub10.setText("0");
        txtsub10.setEnabled(false);
        jPanel4.add(txtsub10);
        txtsub10.setBounds(410, 280, 70, 20);

        btnuevo.setBackground(new java.awt.Color(0, 0, 0));
        btnuevo.setForeground(new java.awt.Color(0, 102, 153));
        btnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/nuevo.png"))); // NOI18N
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });
        jPanel4.add(btnuevo);
        btnuevo.setBounds(80, 360, 80, 30);

        btmodificar.setBackground(new java.awt.Color(0, 0, 0));
        btmodificar.setForeground(new java.awt.Color(0, 102, 153));
        btmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/editar.png"))); // NOI18N
        btmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificarActionPerformed(evt);
            }
        });
        jPanel4.add(btmodificar);
        btmodificar.setBounds(350, 360, 80, 30);

        bteliminar.setBackground(new java.awt.Color(0, 0, 0));
        bteliminar.setForeground(new java.awt.Color(0, 102, 153));
        bteliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/borrar.png"))); // NOI18N
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });
        jPanel4.add(bteliminar);
        bteliminar.setBounds(170, 360, 80, 30);

        btguardar.setBackground(new java.awt.Color(0, 0, 0));
        btguardar.setForeground(new java.awt.Color(0, 102, 153));
        btguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/Save.png"))); // NOI18N
        btguardar.setEnabled(false);
        btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarActionPerformed(evt);
            }
        });
        jPanel4.add(btguardar);
        btguardar.setBounds(260, 360, 80, 30);

        btcancelar.setBackground(new java.awt.Color(0, 0, 0));
        btcancelar.setForeground(new java.awt.Color(0, 102, 153));
        btcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/cancelar.png"))); // NOI18N
        btcancelar.setEnabled(false);
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });
        jPanel4.add(btcancelar);
        btcancelar.setBounds(440, 360, 80, 30);

        jLabel29.setForeground(new java.awt.Color(0, 102, 153));
        jLabel29.setText("Impuesto");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(420, 10, 110, 14);

        jLabel31.setForeground(new java.awt.Color(0, 102, 153));
        jLabel31.setText("Stock");
        jPanel4.add(jLabel31);
        jLabel31.setBounds(520, 10, 110, 14);

        txtstock.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtstock.setForeground(new java.awt.Color(0, 51, 204));
        txtstock.setEnabled(false);
        jPanel4.add(txtstock);
        txtstock.setBounds(510, 30, 80, 20);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(30, 240, 630, 400);

        jcMousePanel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo.jpg"))); // NOI18N
        jcMousePanel3.setVisibleLogo(false);
        jcMousePanel3.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2)));
        jPanel2.setLayout(null);

        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("Cliente");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 30, 120, 14);

        jLabel10.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10.setText("Ruc");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(380, 30, 110, 14);

        jLabel11.setForeground(new java.awt.Color(0, 102, 153));
        jLabel11.setText("Direccion");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 60, 130, 14);

        txtidcliente.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtidcliente.setForeground(new java.awt.Color(0, 102, 204));
        txtidcliente.setEnabled(false);
        txtidcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidclienteActionPerformed(evt);
            }
        });
        txtidcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidclienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidclienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidclienteKeyTyped(evt);
            }
        });
        jPanel2.add(txtidcliente);
        txtidcliente.setBounds(90, 30, 40, 20);

        txtcliente.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtcliente.setForeground(new java.awt.Color(0, 102, 204));
        txtcliente.setEnabled(false);
        jPanel2.add(txtcliente);
        txtcliente.setBounds(140, 30, 170, 20);

        txtruc.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtruc.setForeground(new java.awt.Color(0, 102, 204));
        txtruc.setEnabled(false);
        jPanel2.add(txtruc);
        txtruc.setBounds(440, 30, 150, 20);

        txtdireccion.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtdireccion.setForeground(new java.awt.Color(0, 102, 204));
        txtdireccion.setEnabled(false);
        jPanel2.add(txtdireccion);
        txtdireccion.setBounds(90, 60, 220, 20);

        jLabel12.setForeground(new java.awt.Color(0, 102, 153));
        jLabel12.setText("Telefono");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(370, 60, 150, 14);

        txttelefono.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txttelefono.setForeground(new java.awt.Color(0, 102, 204));
        txttelefono.setEnabled(false);
        jPanel2.add(txttelefono);
        txttelefono.setBounds(440, 60, 150, 20);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 2)));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(null);

        txtempleado.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtempleado.setForeground(new java.awt.Color(0, 204, 204));
        txtempleado.setEnabled(false);
        jPanel1.add(txtempleado);
        txtempleado.setBounds(130, 80, 120, 19);

        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setText("Codigo");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 60, 110, 14);

        jLabel27.setForeground(new java.awt.Color(0, 102, 153));
        jLabel27.setText("Nombre");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(160, 60, 90, 14);

        jLabel28.setForeground(new java.awt.Color(0, 102, 153));
        jLabel28.setText("Encargado");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(100, 40, 160, 14);

        txtidempleado.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtidempleado.setForeground(new java.awt.Color(0, 204, 204));
        txtidempleado.setEnabled(false);
        txtidempleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidempleadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidempleadoKeyTyped(evt);
            }
        });
        jPanel1.add(txtidempleado);
        txtidempleado.setBounds(40, 80, 60, 19);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(310, 170, 310, 150);

        jcMousePanel3.add(jPanel2);
        jPanel2.setBounds(60, 160, 630, 100);

        getContentPane().add(jcMousePanel3);
        jcMousePanel3.setBounds(-30, -20, 720, 750);

        setSize(new java.awt.Dimension(702, 688));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtidempleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidempleadoKeyPressed

    }//GEN-LAST:event_txtidempleadoKeyPressed

    private void txtidempleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidempleadoKeyTyped

    }//GEN-LAST:event_txtidempleadoKeyTyped

    private void txtidclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidclienteActionPerformed

    private void txtidclienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidclienteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtidcliente.getText().isEmpty()) {
                bandera = 1;
                new busqueda_cliente(null, true).setVisible(true);
                bandera = 0;
            } else {
                recuperar_cliente();

            }
        }
    }//GEN-LAST:event_txtidclienteKeyPressed

    private void txtidclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidclienteKeyTyped
        //en caso que se ingrese alguna letra

        if (Character.isDigit(evt.getKeyChar()) == false) {
            evt.consume();
        }
    }//GEN-LAST:event_txtidclienteKeyTyped

    private void txtcodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btagregar.setEnabled(true);
            if (txtcodigo.getText().isEmpty()) {
                bandera = 1;
                new Busqueda_Mercaderia(null, true).setVisible(true);
//                Busqueda_Mercaderia.txtbuscar.requestFocus();
                bandera = 0;
            } else {
                recuperar_mercaderia();
            }
        }
    }//GEN-LAST:event_txtcodigoKeyPressed

    private void txtcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyTyped
        if (Character.isDigit(evt.getKeyChar()) == false) {
            evt.consume();
        }
    }//GEN-LAST:event_txtcodigoKeyTyped

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void txtcantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btagregar.doClick();  //va sobre el boton aceptar
            btguardar.setEnabled(true);
        }
    }//GEN-LAST:event_txtcantidadKeyPressed

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped
        if (Character.isDigit(evt.getKeyChar()) == false) {
            evt.consume();
        }
        if (txtcantidad.getText().length() > 2) {  //ingresa hasta 4 digitos
            evt.consume();

        }
    }//GEN-LAST:event_txtcantidadKeyTyped

    private void btagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btagregarActionPerformed
        if (txtcodigo.getText().trim().isEmpty()) {  //si el campo esta vacio
            JOptionPane.showMessageDialog(null, "El campo esta vacio", "Error", JOptionPane.INFORMATION_MESSAGE);
            txtcodigo.requestFocus();

            return;
        }
        if (txtcantidad.getText().trim().isEmpty() || Integer.parseInt(txtcantidad.getText().trim()) <= 0) {
            JOptionPane.showMessageDialog(null, "Verifique los datos", "Error", JOptionPane.INFORMATION_MESSAGE);
            txtcantidad.requestFocus();

            return;
        }
        String iva5 = "1";
        String iva10 = "2";
        String ivaexenta = "3";
        int vcantidad = 0, vstock = 0;
        vcantidad = Integer.parseInt(txtcantidad.getText().trim());
        vstock = Integer.parseInt(txtstock.getText().trim());

        if (vcantidad > vstock) {
            JOptionPane.showMessageDialog(null, "La cantidad ingresada no puede ser mayor a su stock:.");
            txtcantidad.requestFocus();
            txtcantidad.setText("");
            return;
        }
        int vresultado = 0;
        vresultado = vstock - vcantidad;
        txtstock.setText(formateador.format(vresultado));
        int vsubtotal = Integer.parseInt(txtcantidad.getText()) * Integer.parseInt(txtprecio.getText().replace(".", ""));
        try {
            DefaultTableModel det = (DefaultTableModel) detalle.getModel();

            if (iva5.equals(txtimpuesto.getText())) {
                det.addRow(new Object[]{txtcodigo.getText(),
                    txtdescripcion.getText(),
                    txtcantidad.getText(),
                    txtprecio.getText(),
                    formateador.format(vsubtotal), 0, 0});
                calcular_total3(); //suma iva5

            } else if (iva10.equals(txtimpuesto.getText())) {
                det.addRow(new Object[]{txtcodigo.getText(),
                    txtdescripcion.getText(),
                    txtcantidad.getText(),
                    txtprecio.getText(),
                    0,
                    formateador.format(vsubtotal), 0});
                calcular_total2(); //suma iva 10

            }
            if (txtimpuesto.getText().equals(ivaexenta)) {

                det.addRow(new Object[]{txtcodigo.getText(),
                    txtdescripcion.getText(),
                    txtcantidad.getText(),
                    txtprecio.getText(),
                    0,
                    0,
                    formateador.format(vsubtotal)});
                calcular_total(); //suma exenta

            }

            txtcodigo.setText("");
            txtdescripcion.setText("");
            txtcantidad.setText("");
            txtprecio.setText("");
            txtimpuesto.setText("");
            txtcantidad.setEnabled(false);
            txtcodigo.requestFocus();
            txtstock.setText("");
            suma();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error" + e);
        }
    }//GEN-LAST:event_btagregarActionPerformed

    private void btquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btquitarActionPerformed
        if (detalle.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "No existe detalle", "Error", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (detalle.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar el detalle", "Atencion", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int mensaje = JOptionPane.showConfirmDialog(null, "Desea Quitar la fila seleccionada", "Atencion", JOptionPane.YES_NO_OPTION);
        if (mensaje == JOptionPane.YES_OPTION) {
            DefaultTableModel t = (DefaultTableModel) detalle.getModel();
            t.removeRow(detalle.getSelectedRow());  //fila seleccionada
            calcular_total3(); //suma iva5
            calcular_total2(); //suma iva 10
            calcular_total(); //suma exenta
            suma();
        }
    }//GEN-LAST:event_btquitarActionPerformed

    private void detalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detalleMouseClicked
        btquitar.setEnabled(true);
    }//GEN-LAST:event_detalleMouseClicked

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
        accion = "nuevo";
        bd.autonumerico("pedido_presupuesto", "id_presupuesto", txtn);
        txtidempleado.setText(menu_principal.txtidusuario.getText());
        txtfecha.setText(fec.format(new Date()));
        bd.deshabilitar_botones(btnuevo, btmodificar, bteliminar, btagregar);
        txtidcliente.setEnabled(true);
        //        cbforma.setEnabled(true);
        txtidcliente.requestFocus();
        btcancelar.setEnabled(true);
    }//GEN-LAST:event_btnuevoActionPerformed

    private void btmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificarActionPerformed
        bandera = 1;
        new Busqueda_Presupuesto(null, true).setVisible(true);
        bandera = 0;
        if (!txtn.getText().isEmpty()) {   //!=significa distinto a vacio
            recuperar_datos();
            accion = "modificar";
            bd.deshabilitar_botones(btnuevo, btmodificar, bteliminar, btguardar);
            btcancelar.setEnabled(true);
            txtidcliente.setEnabled(true);
            txtidcliente.requestFocus();
        }
    }//GEN-LAST:event_btmodificarActionPerformed

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
        bandera = 1;
        new Busqueda_Presupuesto(null, true).setVisible(true);
        bandera = 0;
        if (!txtn.getText().isEmpty()) {
            recuperar_datos();
        }
        if (txtn.getText().isEmpty()) {

        } else {

            int mensaje = JOptionPane.showConfirmDialog(null, "Eliminar Registro", "Atencion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            //si es 0 presiono la opcion de si, si es 1 no

            if (mensaje == 0) {
                if (Busqueda_Presupuesto.tabla.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(null, "No hay ningun presupuesto para Eliminar");

                } else {
                    try {
                        String sql = "delete from pedido_presupuesto where id_presupuesto=?";
                        PreparedStatement eli = bd.conexion.prepareStatement(sql);
                        eli.setInt(1, Integer.parseInt(txtn.getText()));
                        eli.execute();
                        btcancelar.setEnabled(true);
                        btcancelar.doClick();
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Error al borrar");

                    }

                }
            }
            if (mensaje == 1) {
                btcancelar.setEnabled(true);
                btcancelar.doClick();
                btcancelar.doClick();
            }
        }
    }//GEN-LAST:event_bteliminarActionPerformed

    private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarActionPerformed
        if (detalle.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Verifique los datos", "Atencion", JOptionPane.QUESTION_MESSAGE);
            return;
        }
        int mensaje = JOptionPane.showConfirmDialog(null, "Desea Guardar", "Atencion", JOptionPane.YES_NO_OPTION);
        if (mensaje == JOptionPane.YES_OPTION) {
            grabar();
        }
    }//GEN-LAST:event_btguardarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        accion = "";
        bd.habilitar_botones(btnuevo, btmodificar, bteliminar, btagregar);

        deshabilitarcampos();
        btcancelar.setEnabled(false);
        btguardar.setEnabled(false);
        btagregar.setEnabled(false);
        btquitar.setEnabled(false);
        limpiarcampos();
        DefaultTableModel tab = (DefaultTableModel) detalle.getModel();
        tab.setRowCount(0);   //limpiamos las filas a cero
        txttotal.setText("0");
    }//GEN-LAST:event_btcancelarActionPerformed

    private void txtidclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidclienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidclienteKeyReleased

    private void txtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnActionPerformed

    private void txtnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnKeyReleased

    }//GEN-LAST:event_txtnKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(presupuest.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(presupuest.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(presupuest.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(presupuest.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new presupuest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btagregar;
    public javax.swing.JButton btcancelar;
    public javax.swing.JButton bteliminar;
    public static javax.swing.JButton btguardar;
    public javax.swing.JButton btmodificar;
    public javax.swing.JButton btnuevo;
    public javax.swing.JButton btquitar;
    public static javax.swing.JTable detalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private jcMousePanel.jcMousePanel jcMousePanel2;
    private jcMousePanel.jcMousePanel jcMousePanel3;
    public static javax.swing.JTextField txtcantidad;
    public static javax.swing.JTextField txtcliente;
    public static javax.swing.JTextField txtcodigo;
    public static javax.swing.JTextField txtdescripcion;
    public static javax.swing.JTextField txtdireccion;
    public javax.swing.JTextField txtempleado;
    public javax.swing.JTextField txtexenta;
    public javax.swing.JTextField txtfecha;
    public static javax.swing.JTextField txtidcliente;
    public javax.swing.JTextField txtidempleado;
    public static javax.swing.JTextField txtimpuesto;
    public javax.swing.JTextField txtiva10;
    public javax.swing.JTextField txtiva5;
    public static javax.swing.JTextField txtn;
    public static javax.swing.JTextField txtprecio;
    public static javax.swing.JTextField txtruc;
    public static javax.swing.JTextField txtstock;
    public javax.swing.JTextField txtsub10;
    public javax.swing.JTextField txtsub5;
    public static javax.swing.JTextField txttelefono;
    public javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

    private void deshabilitarcampos() {
        txtidcliente.setEnabled(false);
        txtcodigo.setEnabled(false);
    }

    private void limpiarcampos() {
        txtcantidad.setText("");
        txtcliente.setText("");
        txtcodigo.setText("");
        txtdescripcion.setText("");
        txtdireccion.setText("");
        txtempleado.setText("");
        txtexenta.setText("0");
        txtfecha.setText("");
        txtidcliente.setText("");
//        txtidempleado.setText("");
        txtimpuesto.setText("");
        txtiva10.setText("0");
        txtiva5.setText("0");
        txtn.setText("");
        txtprecio.setText("");
        txtruc.setText("");
        txtsub10.setText("0");
        txtsub5.setText("0");
        txttelefono.setText("");
        txttotal.setText("0");
    }

    private void recuperar_cliente() {
        try {
            bd.listar_datos("SELECT id_cliente, id_ciudad, cli_nombre, cli_ci, cli_ruc, cli_direc, \n"
                    + "       cli_telef, id_estado\n"
                    + "  FROM cliente"
                    + " where id_cliente =" + txtidcliente.getText()
                    + "");
            if (bd.resultado.next()) {
                txtcliente.setText(bd.resultado.getString("cli_nombre"));
                txtruc.setText(bd.resultado.getString("cli_ruc"));
                txtdireccion.setText(bd.resultado.getString("cli_direc"));
                txttelefono.setText(bd.resultado.getString("cli_telef"));
                txtcodigo.setEnabled(true);
                txtcodigo.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "No existe codigo ingresado\nPor favor verifique", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al recuperar cliente",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void recuperar_mercaderia() {
        try {
            bd.listar_datos("SELECT s.id_articulo as codigo,  s.stock_cant as cantidad, a.art_descri as descripcion,"
                    + "a.art_precioc as precio , a.id_impuesto as impuesto\n"
                    + "  FROM stock s inner join articulos a on a.id_articulo= s.id_articulo"
                    + " where s.id_articulo =" + txtcodigo.getText());
            if (bd.resultado.next()) {
                for (int i = 0; i < detalle.getRowCount(); i++) {
                    String vcod = detalle.getValueAt(i, 0).toString();
                    if (vcod.equals(txtcodigo.getText())) {
                        JOptionPane.showMessageDialog(null, "Codigo Ingresado ya Existe", "Error", JOptionPane.ERROR_MESSAGE);
                        txtcodigo.requestFocus();
                        txtcodigo.setSelectionStart(0);
                        return;
                    }
                }
                txtdescripcion.setText(bd.resultado.getString("descripcion"));
                txtprecio.setText(formateador.format(bd.resultado.getInt("precio")));
                txtimpuesto.setText(bd.resultado.getString("impuesto"));
                txtstock.setText(bd.resultado.getString("cantidad"));
                txtcantidad.setEnabled(true);
                txtcantidad.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "No existe codigo ingresado\nPor favor verifique", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al recuperar mercaderia",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void calcular_total3() {
        int vtot5 = 0;
        for (int i = 0; i < detalle.getRowCount(); i++) {
            //Toma el monto de la columna sub total en la variable vtot
            int vtot = Integer.parseInt(detalle.getValueAt(i, 4).toString().replace(".", ""));
            vtot5 = vtot5 + vtot;
//             vtotexe += vtot;
        }
        txtsub5.setText(formateador.format(vtot5));
    }

    private void calcular_total2() {
        int vtot10 = 0;
        for (int i = 0; i < detalle.getRowCount(); i++) {
            //Toma el monto de la columna sub total en la variable vtot
            int vtot = Integer.parseInt(detalle.getValueAt(i, 5).toString().replace(".", ""));
            vtot10 = vtot10 + vtot;
//             vtot10 += vtot;
        }
        txtsub10.setText(formateador.format(vtot10));
    }

    private void calcular_total() {
        int vexenta = 0;
        for (int i = 0; i < detalle.getRowCount(); i++) {
            //Toma el monto de la columna sub total en la variable vtot
            int vtot = Integer.parseInt(detalle.getValueAt(i, 6).toString().replace(".", ""));
            vexenta = vexenta + vtot;
//             vtot5 += vtot;
        }
        txtexenta.setText(formateador.format(vexenta));
    }

    private void suma() {
        int v5 = 0;
        int v10 = 0;
        int vexe = 0;
        int vsuma = 0;

        v5 = Integer.parseInt(txtsub5.getText().replace(".", ""));
        v10 = Integer.parseInt(txtsub10.getText().replace(".", ""));
        vexe = Integer.parseInt(txtexenta.getText().replace(".", ""));
        vsuma = v5 + v10 + vexe;

        txtiva5.setText(formateador.format(v5 / 21));
        txtiva10.setText(formateador.format(v10 / 11));
        txttotal.setText(formateador.format(vsuma));
    }

    private void grabar() {
        if (accion.equals("nuevo")) {
            try {
                //grabar la cabecera
                String sqlcabecera = "INSERT INTO pedido_presupuesto(\n"
                        + "            id_presupuesto, id_usuario, presu_fecha, id_cliente, presu_monto, \n"
                        + "            id_estado)\n"
                        + "    VALUES (?, ?, ?, ?, ?, \n"
                        + "            ?);";
                PreparedStatement cabecera = bd.conexion.prepareStatement(sqlcabecera);
                cabecera.setInt(1, Integer.parseInt(txtn.getText()));

                cabecera.setDate(3, java.sql.Date.valueOf(convertir_fecha(txtfecha.getText())));
                cabecera.setInt(2, Integer.parseInt(txtidempleado.getText()));
                cabecera.setInt(4, Integer.parseInt(txtidcliente.getText()));
                cabecera.setString(5, txttotal.getText());
                cabecera.setInt(6, 1);
                cabecera.execute();

                //grabar detalle
                String sqldetalle = "INSERT INTO detalle_presupuesto(id_presupuesto, id_articulo,idpresudet, det_cant, det_exenta, det_iva5, \n"
                        + "            det_iva10, det_precio)\n"
                        + "    VALUES (?, ?, ?, ?, ?, \n"
                        + "            ?, ?,?);";

                for (int i = 0; i < detalle.getRowCount(); i++) {
                    String vcodigo = detalle.getValueAt(i, 0).toString();  //0 la columna
                    String vcantidad = detalle.getValueAt(i, 2).toString(); // 2 la columna
                    String vprecio = detalle.getValueAt(i, 3).toString().replace(".", "");    //remplaza el separador de miles
                    String vcinco = detalle.getValueAt(i, 4).toString().replace(".", "");
                    String vdiez = detalle.getValueAt(i, 5).toString().replace(".", "");
                    String vexenta = detalle.getValueAt(i, 6).toString().replace(".", "");
                    grabar_detalle(sqldetalle, vcodigo, vcantidad, vprecio, vcinco, vdiez, vexenta);

                }

                btcancelar.doClick();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "error al grabar" + ex);
            }
        } else {
//                para modificar la bd primero hay que eliminar el registro
//                para que pueda volver a asignar un nuevo registro
            try {
                String sqll = "delete from pedido_presupuesto where id_presupuesto=?";
                PreparedStatement eli = bd.conexion.prepareStatement(sqll);
                eli.setInt(1, Integer.parseInt(txtn.getText()));
                eli.execute();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al borrar");
            }
//            //INSERT
            try {
                //grabar la cabecera
                String sqlcabecera = "INSERT INTO pedido_presupuesto(\n"
                        + "            id_presupuesto, id_usuario, presu_fecha, id_cliente, presu_monto, \n"
                        + "            id_estado)\n"
                        + "    VALUES (?, ?, ?, ?, ?, \n"
                        + "            ?);";
                PreparedStatement cabecera = bd.conexion.prepareStatement(sqlcabecera);
                cabecera.setInt(1, Integer.parseInt(txtn.getText()));
                cabecera.setDate(3, java.sql.Date.valueOf(convertir_fecha(txtfecha.getText())));
                cabecera.setInt(2, Integer.parseInt(txtidempleado.getText()));
                cabecera.setInt(4, Integer.parseInt(txtidcliente.getText()));
                cabecera.setString(5, txttotal.getText());
                cabecera.setInt(6, 1);
                cabecera.execute();

                //grabar detalle
                String sqldetalle = "INSERT INTO detalle_presupuesto(id_presupuesto, id_articulo,idpresudet, det_cant, det_exenta, det_iva5, \n"
                        + "            det_iva10, det_precio)\n"
                        + "    VALUES (?, ?, ?, ?, ?, \n"
                        + "            ?, ?,?);";

                for (int i = 0; i < detalle.getRowCount(); i++) {
                    String vcodigo = detalle.getValueAt(i, 0).toString();  //0 la columna
                    String vcantidad = detalle.getValueAt(i, 2).toString(); // 2 la columna
                    String vprecio = detalle.getValueAt(i, 3).toString().replace(".", "");    //remplaza el separador de miles
                    String vcinco = detalle.getValueAt(i, 4).toString().replace(".", "");
                    String vdiez = detalle.getValueAt(i, 5).toString().replace(".", "");
                    String vexenta = detalle.getValueAt(i, 6).toString().replace(".", "");
                    grabar_detalle(sqldetalle, vcodigo, vcantidad, vprecio, vcinco, vdiez, vexenta);

                }

                btcancelar.doClick();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "error al grabar" + ex);
            }

        }
    }

    private void grabar_detalle(String sqldetalle, String vcodigo, String vcantidad, String vprecio, String vcinco, String vdiez, String vexenta) {
        int vidpresupuesto = 0;
        try {
            bd.listar_datos("select nextval('idpresupuestodetalle')as codigo");
            bd.resultado.next();
            vidpresupuesto = bd.resultado.getInt("codigo");
        } catch (Exception e) {
        }
        try {
            PreparedStatement detalle1 = bd.conexion.prepareStatement(sqldetalle);
            detalle1.setInt(3, vidpresupuesto);
            detalle1.setInt(1, Integer.parseInt(txtn.getText()));
            detalle1.setInt(2, Integer.parseInt(vcodigo));
            detalle1.setInt(4, Integer.parseInt(vcantidad));
            detalle1.setInt(8, Integer.parseInt(vprecio));
            detalle1.setInt(6, Integer.parseInt(vcinco));
            detalle1.setInt(7, Integer.parseInt(vdiez));
            detalle1.setInt(5, Integer.parseInt(vexenta));
            detalle1.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al grabar detalle" + e);
        }
    }

    private String convertir_fecha(String fecha) {
        // 25-08-2017
        String dia = "", mes = "", anho = "";

        dia = fecha.substring(0, 2);
        mes = fecha.substring(3, 5);
        anho = fecha.substring(6, 10);
        fecha = anho + "-" + mes + "-" + dia;

        return fecha;
    }

    private void recuperar_datos() {
        DefaultTableModel dt = (DefaultTableModel) detalle.getModel();
        dt.setRowCount(0);
        try {
            bd.listar_datos("SELECT presupuesto, codigo, articulo, idpresudet, cantidad, exenta, \n"
                    + "       iva5, iva10, precio, fecha, cliente, nombre, ruc, direccion, \n"
                    + "       telefono, monto, estado\n"
                    + "  FROM v_presupuessto  where estado=1 and(presupuesto=" + txtn.getText() + ");");
            if (bd.resultado.next()) {

                txtfecha.setText(fec.format(bd.resultado.getDate("fecha")));
                txtidcliente.setText(bd.resultado.getString("cliente"));
                txtcliente.setText(bd.resultado.getString("nombre"));
                txtruc.setText(bd.resultado.getString("ruc"));
                txtdireccion.setText(bd.resultado.getString("direccion"));
                txttelefono.setText(bd.resultado.getString("telefono"));

                do {
                    dt.addRow(new Object[]{bd.resultado.getString("codigo"),
                        bd.resultado.getString("articulo"),
                        bd.resultado.getString("cantidad"),
                        formateador.format(bd.resultado.getInt("precio")),
                        formateador.format(bd.resultado.getInt("iva5")),
                        formateador.format(bd.resultado.getInt("iva10")),
                        formateador.format(bd.resultado.getInt("exenta")),});
                } while (bd.resultado.next());
                calcular_total();
                calcular_total2();
                calcular_total3();
                suma();
                txtcodigo.setEnabled(true);
                btguardar.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al recuperar datos" + e);
        }
    }
}
