/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movimiento_ventas;

import conexion.conexion;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matrix
 */
public class tipocobro extends javax.swing.JDialog {

    String accion = "";
    conexion bd = new conexion();
    public static int bandera = 0;

    public tipocobro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bd.conecta();
        ver();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtguaranies = new javax.swing.JTextField();
        txtcheque = new javax.swing.JTextField();
        txttarjeta = new javax.swing.JTextField();
        txtnumerocheque = new javax.swing.JTextField();
        txtbancocheque = new javax.swing.JTextField();
        txtnumerotarjeta = new javax.swing.JTextField();
        txtbancotarjeta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtmonto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbtipo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jcMousePanel1 = new jcMousePanel.jcMousePanel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cobro");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102))));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Guaranies:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 80, 150, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Tarjeta");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 190, 150, 17);

        txtguaranies.setText("0");
        txtguaranies.setEnabled(false);
        txtguaranies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtguaraniesActionPerformed(evt);
            }
        });
        txtguaranies.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtguaraniesKeyPressed(evt);
            }
        });
        jPanel1.add(txtguaranies);
        txtguaranies.setBounds(150, 70, 130, 30);

        txtcheque.setText("00");
        txtcheque.setEnabled(false);
        txtcheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtchequeActionPerformed(evt);
            }
        });
        jPanel1.add(txtcheque);
        txtcheque.setBounds(150, 120, 130, 30);

        txttarjeta.setText("00");
        txttarjeta.setEnabled(false);
        jPanel1.add(txttarjeta);
        txttarjeta.setBounds(150, 180, 130, 30);

        txtnumerocheque.setText("0");
        txtnumerocheque.setEnabled(false);
        jPanel1.add(txtnumerocheque);
        txtnumerocheque.setBounds(300, 120, 90, 30);

        txtbancocheque.setText("0");
        txtbancocheque.setEnabled(false);
        txtbancocheque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbancochequeKeyPressed(evt);
            }
        });
        jPanel1.add(txtbancocheque);
        txtbancocheque.setBounds(410, 120, 110, 30);

        txtnumerotarjeta.setText("0");
        txtnumerotarjeta.setEnabled(false);
        jPanel1.add(txtnumerotarjeta);
        txtnumerotarjeta.setBounds(300, 180, 90, 30);

        txtbancotarjeta.setText("0");
        txtbancotarjeta.setEnabled(false);
        txtbancotarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbancotarjetaKeyPressed(evt);
            }
        });
        jPanel1.add(txtbancotarjeta);
        txtbancotarjeta.setBounds(410, 180, 110, 30);

        jLabel5.setText("Nº de Cheque");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(300, 100, 160, 14);

        jLabel6.setText("Banco");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(440, 100, 110, 14);

        jLabel7.setText("Nº de Boleta");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(310, 160, 150, 14);

        jLabel8.setText("Banco");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(440, 160, 110, 14);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/ok.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(260, 230, 90, 30);

        txtmonto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtmonto.setForeground(new java.awt.Color(204, 0, 0));
        txtmonto.setText("200");
        txtmonto.setEnabled(false);
        jPanel1.add(txtmonto);
        txtmonto.setBounds(310, 20, 140, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Monto Total");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(160, 30, 160, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Cheque");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 130, 150, 17);

        cbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guaranies", "Cheque", "Tarjeta" }));
        cbtipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbtipoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbtipoMousePressed(evt);
            }
        });
        cbtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtipoActionPerformed(evt);
            }
        });
        cbtipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbtipoKeyPressed(evt);
            }
        });
        jPanel1.add(cbtipo);
        cbtipo.setBounds(16, 30, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 30, 620, 280);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Cobro");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(260, 0, 120, 22);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo.jpg"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);
        getContentPane().add(jcMousePanel1);
        jcMousePanel1.setBounds(-60, -90, 720, 450);

        setSize(new java.awt.Dimension(665, 365));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtguaranies.getText().isEmpty()) {
            txtguaranies.setText("0");
        }
        if (txtcheque.getText().isEmpty()) {
            txtcheque.setText("0");
        }
        if (txttarjeta.getText().isEmpty()) {
            txttarjeta.setText("0");
        }
        if (txtbancocheque.getText().isEmpty()) {
            txtbancocheque.setText("0");
        }
        if (txtbancotarjeta.getText().isEmpty()) {
            txtbancotarjeta.setText("0");
        }
        if (txtnumerocheque.getText().isEmpty()) {
            txtnumerocheque.setText("0");
        }
        if (txtnumerotarjeta.getText().isEmpty()) {
            txtnumerotarjeta.setText("0");
        }
        int suma = 0;
        int vguaranies = 0;
        int vcheque = 0;
        int vtarjeta = 0;
        int vtotal = 0;
        int vbancocheque = 0;
        int vbancotarjeta = 0;
        vguaranies = Integer.parseInt(txtguaranies.getText().replace(".", ""));
        vcheque = Integer.parseInt(txtcheque.getText().replace(".", ""));
        vtarjeta = Integer.parseInt(txttarjeta.getText().replace(".", ""));
        suma = vguaranies + vcheque + vtarjeta;
        vtotal = Integer.parseInt(txtmonto.getText().replace(".", ""));
        vbancocheque = Integer.parseInt(txtbancocheque.getText());
        vbancotarjeta = Integer.parseInt(txtbancotarjeta.getText());
        if (suma < vtotal) {
            JOptionPane.showMessageDialog(null, "Verique Monto a Cobrar");

            return;

        }
        if (vcheque > 0) {
            JOptionPane.showMessageDialog(null, "Ingrese Datos de Cheque y Seleccione Banco");
            txtcheque.requestFocus();
            if (txtnumerocheque.getText().equals("0")) {
//                JOptionPane.showMessageDialog(null, "Ingrese Datos de Bancos");
                txtnumerocheque.requestFocus();
                return;
            }
            if (txtbancocheque.getText().equals("0")) {
//                JOptionPane.showMessageDialog(null, "Ingrese Datos de Bancos");
                txtbancocheque.requestFocus();
                return;
            }
        } else {
            if (vtarjeta > 0) {
                JOptionPane.showMessageDialog(null, "Ingrese Datos de Tarjeta y Seleccione Banco");
                txtnumerotarjeta.requestFocus();
                if (txtbancotarjeta.getText().equals("0")) {
//                JOptionPane.showMessageDialog(null, "Ingrese Banco");
                    txtnumerotarjeta.requestFocus();
                    return;
                }
            }
        }

        DefaultTableModel det = (DefaultTableModel) Ventas.tipocobro.getModel();

        det.addRow(new Object[]{Ventas.txtn.getText(), "1", 0, 0, txtguaranies.getText(),});
        det.addRow(new Object[]{Ventas.txtn.getText(), "2", txtbancocheque.getText(), txtnumerocheque.getText(), txtcheque.getText(),});
        det.addRow(new Object[]{Ventas.txtn.getText(), "3", txtbancotarjeta.getText(), txtnumerotarjeta.getText(), txttarjeta.getText()});
        if (Ventas.txtpresupuesto.getText().isEmpty()) {
            Ventas.txtpresupuesto.setText("0");
        }

        Ventas.btok.doClick();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtchequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtchequeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtchequeActionPerformed

    private void txtguaraniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtguaraniesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtguaraniesActionPerformed

    private void cbtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtipoActionPerformed

    }//GEN-LAST:event_cbtipoActionPerformed

    private void cbtipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbtipoKeyPressed
        verificar();

//        if (cbtipo.getSelectedItem().equals("Tarjeta") || cbtipo.getSelectedItem().equals("Cheque")) {
//            if (cbtipo.getSelectedItem().equals("Cheque")) {
//                StringBuffer v = new StringBuffer();
//                v.append("1) No permitido cheques de terceros ajenos  al cliente \n \n");
//                v.append("2) Cheque ya confeccionado y firmado , Solicitar una firma en la parte posterior \n \n");
//                v.append("3) Solicitar C.I y fotocopiar \n \n");
//                v.append("4) Verificar si el cheque es adelantado o diferido ");
//                JOptionPane.showMessageDialog(null, v, "Atenci�n!!!", JOptionPane.WARNING_MESSAGE);
//
//            }
//
//            txtguaranies.requestFocus();
//        }
    }//GEN-LAST:event_cbtipoKeyPressed

    private void cbtipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbtipoMouseClicked
        verificar();
        //if (cbtipo.getSelectedItem().equals("Tarjeta") || cbtipo.getSelectedItem().equals("Cheque")) {
//            if (cbtipo.getSelectedItem().equals("Cheque")) {
//                StringBuffer v = new StringBuffer();
//                v.append("1) No permitido cheques de terceros ajenos  al cliente \n \n");
//                v.append("2) Cheque ya confeccionado y firmado , Solicitar una firma en la parte posterior \n \n");
//                v.append("3) Solicitar C.I y fotocopiar \n \n");
//                v.append("4) Verificar si el cheque es adelantado o diferido ");
//                JOptionPane.showMessageDialog(null, v, "Atenci�n!!!", JOptionPane.WARNING_MESSAGE);
//
//            }
////        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
////            
////                
////            }
////            txtguaranies.requestFocus();
////        }
    }//GEN-LAST:event_cbtipoMouseClicked

    private void txtguaraniesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtguaraniesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButton1.doClick();
        }
        calculo();
    }//GEN-LAST:event_txtguaraniesKeyPressed

    private void cbtipoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbtipoMousePressed
        verificar();
    }//GEN-LAST:event_cbtipoMousePressed

    private void txtbancochequeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbancochequeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtbancocheque.getText().equals("0")) {
                bandera = 1;
                new buscadores.buscador_banco(null, true).setVisible(true);
                bandera = 0;
            }
        }
    }//GEN-LAST:event_txtbancochequeKeyPressed

    private void txtbancotarjetaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbancotarjetaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtbancotarjeta.getText().equals("0")) {
                bandera = 2;
                new buscadores.buscador_banco(null, true).setVisible(true);
                bandera = 0;
            }
        }
    }//GEN-LAST:event_txtbancotarjetaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tipocobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tipocobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tipocobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tipocobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tipocobro dialog = new tipocobro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbtipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    public static javax.swing.JTextField txtbancocheque;
    public static javax.swing.JTextField txtbancotarjeta;
    private javax.swing.JTextField txtcheque;
    private javax.swing.JTextField txtguaranies;
    private javax.swing.JTextField txtmonto;
    private javax.swing.JTextField txtnumerocheque;
    private javax.swing.JTextField txtnumerotarjeta;
    private javax.swing.JTextField txttarjeta;
    // End of variables declaration//GEN-END:variables

    private void ver() {
        if (Ventas.bandera == 1) {
            txtmonto.setText(Ventas.txttotal.getText());
        }

    }

    private void calculo() {

    }

    private void verificar() {
        if (cbtipo.getSelectedItem().equals("Guaranies")) {
            txtguaranies.setEnabled(true);
            txtguaranies.requestFocus();
            txtnumerotarjeta.setEnabled(false);
            txtbancotarjeta.setEnabled(false);
            txtnumerocheque.setEnabled(false);
            txtbancocheque.setEnabled(false);
            txttarjeta.setEnabled(false);
            txtcheque.setEnabled(false);
        }
        if (cbtipo.getSelectedItem().equals("Tarjeta")) {
            txttarjeta.setEnabled(true);
            txtnumerotarjeta.setEnabled(true);
            txtbancotarjeta.setEnabled(true);
            txttarjeta.requestFocus();

            txtguaranies.setEnabled(false);
            txtcheque.setEnabled(false);

            txtnumerocheque.setEnabled(false);
            txtbancocheque.setEnabled(false);
        }
        if (cbtipo.getSelectedItem().equals("Cheque")) {
            txtcheque.setEnabled(true);
            txtcheque.requestFocus();
            txtnumerocheque.setEnabled(true);
            txtbancocheque.setEnabled(true);

            txtguaranies.setEnabled(false);
            txttarjeta.setEnabled(false);

            txtnumerotarjeta.setEnabled(false);
            txtbancotarjeta.setEnabled(false);

        }

    }

}
