/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movimiento_ventas;

import conexion.conexion;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import menu.menu_principal;
import referenciales.Articulos;

/**
 *
 * @author Matrix
 */
public class Ventas extends javax.swing.JFrame {

    String accion = "";
    conexion bd = new conexion();
    SimpleDateFormat fec = new SimpleDateFormat("dd/MM/yyyy"); //formato para fecha
    DecimalFormat formateador = new DecimalFormat("#,##0"); //formato para separador de miles
    //variable estatico para poder ver en otros formularios
    public static int bandera = 0;

    public Ventas() {
        initComponents();
        bd.conecta();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jcMousePanel2 = new jcMousePanel.jcMousePanel();
        txtidcliente = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtruc = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        cbforma = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        txtpresupuesto = new javax.swing.JTextField();
        txtidclient = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtempleado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtidempleado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtidapertura = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txttimbrado = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtinicio = new javax.swing.JTextField();
        txtfactura = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtn = new javax.swing.JTextField();
        txtidtimbrado = new javax.swing.JTextField();
        txtfin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtsumatim = new javax.swing.JTextField();
        txtidbanco = new javax.swing.JTextField();
        txtnroboleta = new javax.swing.JTextField();
        txtdetmonto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tipocobro = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        btagregar = new javax.swing.JButton();
        btquitar = new javax.swing.JButton();
        txtimpuesto = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detalle = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtsub5 = new javax.swing.JTextField();
        txtiva5 = new javax.swing.JTextField();
        txtiva10 = new javax.swing.JTextField();
        txtexenta = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtsub10 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtiddeposito = new javax.swing.JTextField();
        txtdeposito = new javax.swing.JTextField();
        jcMousePanel3 = new jcMousePanel.jcMousePanel();
        jPanel3 = new javax.swing.JPanel();
        btnuevo = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        btguardar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        btok = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel36.setText("jLabel36");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Factura::.");
        setResizable(false);
        getContentPane().setLayout(null);

        txtidcliente.setBackground(new java.awt.Color(255, 255, 255));
        txtidcliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2)));
        txtidcliente.setLayout(null);

        jLabel14.setForeground(new java.awt.Color(0, 102, 153));
        jLabel14.setText("Condicion de Pago ");
        txtidcliente.add(jLabel14);
        jLabel14.setBounds(340, 20, 170, 20);

        txtfecha.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtfecha.setForeground(new java.awt.Color(0, 153, 204));
        txtfecha.setEnabled(false);
        txtidcliente.add(txtfecha);
        txtfecha.setBounds(150, 20, 160, 19);

        jLabel38.setForeground(new java.awt.Color(0, 102, 153));
        jLabel38.setText("Nombre o Razon Social");
        txtidcliente.add(jLabel38);
        jLabel38.setBounds(10, 50, 150, 20);

        txtcliente.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtcliente.setForeground(new java.awt.Color(0, 153, 204));
        txtcliente.setEnabled(false);
        txtidcliente.add(txtcliente);
        txtcliente.setBounds(210, 50, 350, 19);

        jLabel39.setForeground(new java.awt.Color(0, 102, 153));
        jLabel39.setText("RUC o C.I");
        txtidcliente.add(jLabel39);
        jLabel39.setBounds(10, 80, 150, 20);

        txtruc.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtruc.setForeground(new java.awt.Color(0, 153, 204));
        txtruc.setEnabled(false);
        txtidcliente.add(txtruc);
        txtruc.setBounds(150, 80, 160, 19);

        jLabel40.setForeground(new java.awt.Color(0, 102, 153));
        jLabel40.setText("Direccion");
        txtidcliente.add(jLabel40);
        jLabel40.setBounds(10, 110, 150, 20);

        txtdireccion.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtdireccion.setForeground(new java.awt.Color(0, 153, 204));
        txtdireccion.setEnabled(false);
        txtidcliente.add(txtdireccion);
        txtdireccion.setBounds(150, 110, 160, 19);

        jLabel41.setForeground(new java.awt.Color(0, 102, 153));
        jLabel41.setText("Telefono");
        txtidcliente.add(jLabel41);
        jLabel41.setBounds(340, 110, 130, 20);

        txttelefono.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txttelefono.setForeground(new java.awt.Color(0, 153, 204));
        txttelefono.setEnabled(false);
        txtidcliente.add(txttelefono);
        txttelefono.setBounds(450, 110, 110, 20);

        jLabel42.setForeground(new java.awt.Color(0, 102, 153));
        jLabel42.setText("Fecha de Emision");
        txtidcliente.add(jLabel42);
        jLabel42.setBounds(10, 20, 150, 20);

        cbforma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contado", "Credito" }));
        cbforma.setToolTipText("");
        cbforma.setEnabled(false);
        txtidcliente.add(cbforma);
        cbforma.setBounds(460, 20, 100, 20);

        jLabel43.setForeground(new java.awt.Color(0, 102, 153));
        jLabel43.setText("Nº Presupuesto");
        txtidcliente.add(jLabel43);
        jLabel43.setBounds(340, 80, 170, 20);

        txtpresupuesto.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtpresupuesto.setForeground(new java.awt.Color(0, 153, 204));
        txtpresupuesto.setEnabled(false);
        txtpresupuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpresupuestoKeyPressed(evt);
            }
        });
        txtidcliente.add(txtpresupuesto);
        txtpresupuesto.setBounds(450, 80, 110, 19);

        txtidclient.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtidclient.setForeground(new java.awt.Color(0, 51, 204));
        txtidclient.setEnabled(false);
        txtidclient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidclientKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidclientKeyTyped(evt);
            }
        });
        txtidcliente.add(txtidclient);
        txtidclient.setBounds(150, 50, 50, 20);

        getContentPane().add(txtidcliente);
        txtidcliente.setBounds(30, 180, 640, 140);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 2)));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(null);

        txtempleado.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtempleado.setForeground(new java.awt.Color(0, 204, 204));
        txtempleado.setEnabled(false);
        jPanel1.add(txtempleado);
        txtempleado.setBounds(140, 260, 120, 19);

        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setText("Codigo");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 240, 60, 14);

        jLabel27.setForeground(new java.awt.Color(0, 102, 153));
        jLabel27.setText("Nombre");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(170, 240, 37, 14);

        jLabel28.setForeground(new java.awt.Color(0, 102, 153));
        jLabel28.setText("Apertura");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(340, 230, 110, 14);

        txtidempleado.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtidempleado.setForeground(new java.awt.Color(0, 204, 204));
        txtidempleado.setEnabled(false);
        txtidempleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidempleadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidempleadoKeyTyped(evt);
            }
        });
        jPanel1.add(txtidempleado);
        txtidempleado.setBounds(50, 260, 60, 19);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("EcoLuz Comercial");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 10, 390, 60);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("De Julio Cesar Romero Lopez");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 70, 210, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Cerro Cora Nº 253 c/ Iturbe");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(90, 110, 200, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Venta de Materiales Electricos");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(90, 90, 210, 17);
        jPanel1.add(txtidapertura);
        txtidapertura.setBounds(340, 250, 50, 20);

        jLabel30.setForeground(new java.awt.Color(0, 102, 153));
        jLabel30.setText("Empleado");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(100, 210, 110, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 10, 360, 170);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2)));
        jPanel2.setLayout(null);

        jLabel12.setText("Fecha fin Vigente:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 80, 170, 14);

        txttimbrado.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txttimbrado.setEnabled(false);
        jPanel2.add(txttimbrado);
        txttimbrado.setBounds(150, 20, 120, 19);

        jLabel32.setText("Timbrado Nº:");
        jPanel2.add(jLabel32);
        jLabel32.setBounds(50, 20, 120, 14);

        jLabel33.setText("Fecha de Inicio Vigente:");
        jPanel2.add(jLabel33);
        jLabel33.setBounds(10, 50, 180, 14);

        txtinicio.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtinicio.setEnabled(false);
        jPanel2.add(txtinicio);
        txtinicio.setBounds(150, 50, 120, 19);

        txtfactura.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtfactura.setEnabled(false);
        txtfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfacturaActionPerformed(evt);
            }
        });
        jPanel2.add(txtfactura);
        txtfactura.setBounds(320, 60, 60, 20);

        jLabel34.setText("RUC ");
        jPanel2.add(jLabel34);
        jLabel34.setBounds(100, 110, 60, 14);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 102, 102));
        jLabel35.setText("Factura");
        jPanel2.add(jLabel35);
        jLabel35.setBounds(40, 130, 90, 22);

        jLabel37.setText("5422361-0");
        jPanel2.add(jLabel37);
        jLabel37.setBounds(160, 104, 110, 20);

        txtn.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtn.setForeground(new java.awt.Color(0, 153, 204));
        txtn.setEnabled(false);
        jPanel2.add(txtn);
        txtn.setBounds(150, 130, 120, 19);

        txtidtimbrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidtimbradoKeyReleased(evt);
            }
        });
        jPanel2.add(txtidtimbrado);
        txtidtimbrado.setBounds(310, 10, 40, 20);

        txtfin.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtfin.setEnabled(false);
        txtfin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfinActionPerformed(evt);
            }
        });
        jPanel2.add(txtfin);
        txtfin.setBounds(150, 80, 120, 20);

        jLabel1.setText("numero de tabla fact");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(300, 40, 140, 14);
        jPanel2.add(txtsumatim);
        txtsumatim.setBounds(366, 10, 30, 20);
        jPanel2.add(txtidbanco);
        txtidbanco.setBounds(510, 40, 50, 20);
        jPanel2.add(txtnroboleta);
        txtnroboleta.setBounds(570, 40, 40, 20);
        jPanel2.add(txtdetmonto);
        txtdetmonto.setBounds(510, 70, 60, 20);

        tipocobro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "factura", "tipo", "banco", "nroboleta", "monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tipocobro);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(390, 120, 290, 120);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(390, 10, 280, 170);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2)));
        jPanel4.setEnabled(false);
        jPanel4.setLayout(null);

        jLabel15.setForeground(new java.awt.Color(0, 102, 153));
        jLabel15.setText("Codigo");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(90, 10, 130, 14);

        jLabel16.setForeground(new java.awt.Color(0, 102, 153));
        jLabel16.setText("Producto");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(190, 10, 140, 14);

        jLabel17.setForeground(new java.awt.Color(0, 102, 153));
        jLabel17.setText("Deposito");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(650, 140, 120, 14);

        jLabel18.setForeground(new java.awt.Color(0, 102, 153));
        jLabel18.setText("Cantidad");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(340, 10, 140, 14);

        txtdescripcion.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtdescripcion.setForeground(new java.awt.Color(0, 51, 204));
        txtdescripcion.setEnabled(false);
        jPanel4.add(txtdescripcion);
        txtdescripcion.setBounds(150, 30, 160, 20);

        txtprecio.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtprecio.setForeground(new java.awt.Color(0, 51, 204));
        txtprecio.setEnabled(false);
        jPanel4.add(txtprecio);
        txtprecio.setBounds(410, 30, 120, 20);

        txtcantidad.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtcantidad.setForeground(new java.awt.Color(0, 51, 204));
        txtcantidad.setEnabled(false);
        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });
        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });
        jPanel4.add(txtcantidad);
        txtcantidad.setBounds(330, 30, 60, 20);

        btagregar.setText("Agregar");
        btagregar.setEnabled(false);
        btagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btagregarActionPerformed(evt);
            }
        });
        jPanel4.add(btagregar);
        btagregar.setBounds(220, 70, 71, 20);

        btquitar.setText("Quitar");
        btquitar.setEnabled(false);
        btquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btquitarActionPerformed(evt);
            }
        });
        jPanel4.add(btquitar);
        btquitar.setBounds(300, 70, 70, 23);

        txtimpuesto.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtimpuesto.setForeground(new java.awt.Color(0, 51, 204));
        txtimpuesto.setEnabled(false);
        jPanel4.add(txtimpuesto);
        txtimpuesto.setBounds(640, 100, 80, 20);

        jLabel24.setText("Impuestos");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(410, 90, 70, 14);

        detalle.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2)));
        detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Cantidad", "Precio", "5%", "10%", "Exenta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detalleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(detalle);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 550, 160);

        jLabel19.setForeground(new java.awt.Color(0, 102, 153));
        jLabel19.setText("Sub total");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(250, 290, 100, 14);

        jLabel20.setForeground(new java.awt.Color(0, 102, 153));
        jLabel20.setText("Total Impuesto");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(70, 280, 90, 14);

        jLabel21.setForeground(new java.awt.Color(0, 102, 153));
        jLabel21.setText("Total a Pagar");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(250, 320, 90, 14);

        txtsub5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtsub5.setForeground(new java.awt.Color(0, 51, 204));
        txtsub5.setText("0");
        txtsub5.setEnabled(false);
        jPanel4.add(txtsub5);
        txtsub5.setBounds(330, 280, 60, 20);

        txtiva5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtiva5.setForeground(new java.awt.Color(0, 51, 204));
        txtiva5.setText("0");
        txtiva5.setEnabled(false);
        jPanel4.add(txtiva5);
        txtiva5.setBounds(30, 320, 60, 20);

        txtiva10.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtiva10.setForeground(new java.awt.Color(0, 51, 204));
        txtiva10.setText("0");
        txtiva10.setEnabled(false);
        jPanel4.add(txtiva10);
        txtiva10.setBounds(120, 320, 80, 20);

        txtexenta.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtexenta.setForeground(new java.awt.Color(0, 51, 204));
        txtexenta.setText("0");
        txtexenta.setEnabled(false);
        jPanel4.add(txtexenta);
        txtexenta.setBounds(500, 280, 60, 20);

        txttotal.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txttotal.setForeground(new java.awt.Color(0, 51, 204));
        txttotal.setText("0");
        txttotal.setEnabled(false);
        jPanel4.add(txttotal);
        txttotal.setBounds(390, 320, 140, 20);

        jLabel25.setText("5%");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(50, 300, 50, 14);

        jLabel26.setText("10%");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(140, 300, 60, 14);

        txtsub10.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtsub10.setForeground(new java.awt.Color(0, 51, 204));
        txtsub10.setText("0");
        txtsub10.setEnabled(false);
        jPanel4.add(txtsub10);
        txtsub10.setBounds(410, 280, 70, 20);

        jLabel29.setForeground(new java.awt.Color(0, 102, 153));
        jLabel29.setText("Impuesto");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(650, 80, 70, 14);

        jLabel31.setForeground(new java.awt.Color(0, 102, 153));
        jLabel31.setText("Stock");
        jPanel4.add(jLabel31);
        jLabel31.setBounds(660, 10, 70, 14);

        txtstock.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtstock.setForeground(new java.awt.Color(0, 51, 204));
        txtstock.setEnabled(false);
        jPanel4.add(txtstock);
        txtstock.setBounds(650, 30, 80, 20);

        txtcodigo.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtcodigo.setForeground(new java.awt.Color(0, 51, 204));
        txtcodigo.setEnabled(false);
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoKeyTyped(evt);
            }
        });
        jPanel4.add(txtcodigo);
        txtcodigo.setBounds(80, 30, 60, 20);

        jLabel22.setForeground(new java.awt.Color(0, 102, 153));
        jLabel22.setText("Precio");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(430, 10, 130, 14);

        txtiddeposito.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtiddeposito.setForeground(new java.awt.Color(0, 51, 204));
        txtiddeposito.setText("1");
        txtiddeposito.setEnabled(false);
        txtiddeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtiddepositoActionPerformed(evt);
            }
        });
        txtiddeposito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtiddepositoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtiddepositoKeyTyped(evt);
            }
        });
        jPanel4.add(txtiddeposito);
        txtiddeposito.setBounds(660, 170, 40, 20);

        txtdeposito.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtdeposito.setForeground(new java.awt.Color(0, 51, 204));
        txtdeposito.setEnabled(false);
        jPanel4.add(txtdeposito);
        txtdeposito.setBounds(650, 220, 80, 20);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(30, 320, 640, 360);

        jcMousePanel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Principal.jpg"))); // NOI18N
        jcMousePanel3.setVisibleLogo(false);
        jcMousePanel3.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jPanel3.setLayout(null);

        btnuevo.setBackground(new java.awt.Color(0, 0, 0));
        btnuevo.setForeground(new java.awt.Color(0, 255, 255));
        btnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/nuevo.png"))); // NOI18N
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });
        jPanel3.add(btnuevo);
        btnuevo.setBounds(10, 10, 110, 40);

        bteliminar.setBackground(new java.awt.Color(0, 0, 0));
        bteliminar.setForeground(new java.awt.Color(0, 255, 255));
        bteliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/borrar.png"))); // NOI18N
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });
        jPanel3.add(bteliminar);
        bteliminar.setBounds(10, 60, 110, 40);

        btguardar.setBackground(new java.awt.Color(0, 0, 0));
        btguardar.setForeground(new java.awt.Color(0, 255, 255));
        btguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/Save.png"))); // NOI18N
        btguardar.setEnabled(false);
        btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarActionPerformed(evt);
            }
        });
        jPanel3.add(btguardar);
        btguardar.setBounds(10, 110, 110, 40);

        btcancelar.setBackground(new java.awt.Color(0, 0, 0));
        btcancelar.setForeground(new java.awt.Color(0, 255, 255));
        btcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icon/cancelar.png"))); // NOI18N
        btcancelar.setEnabled(false);
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btcancelar);
        btcancelar.setBounds(10, 160, 110, 40);

        btok.setText("OK");
        btok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btokActionPerformed(evt);
            }
        });
        jPanel3.add(btok);
        btok.setBounds(130, 90, 80, 23);

        jcMousePanel3.add(jPanel3);
        jPanel3.setBounds(670, 470, 130, 210);

        getContentPane().add(jcMousePanel3);
        jcMousePanel3.setBounds(0, 0, 900, 700);

        setSize(new java.awt.Dimension(833, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtidempleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidempleadoKeyPressed

    }//GEN-LAST:event_txtidempleadoKeyPressed

    private void txtidempleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidempleadoKeyTyped

    }//GEN-LAST:event_txtidempleadoKeyTyped

    private void txtidclientKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidclientKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {

            if (txtidclient.getText().isEmpty()) {
                bandera = 1;
               new bucador_clientefact().setVisible(true);
//                busqueda_cliente.txtbuscar.requestFocus();
                bandera = 0;
            } else {
                recuperar_cliente();
            }
        }


    }//GEN-LAST:event_txtidclientKeyPressed

    private void txtidclientKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidclientKeyTyped
        if (Character.isDigit(evt.getKeyChar()) == false) {
            evt.consume();
        }
    }//GEN-LAST:event_txtidclientKeyTyped

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void txtcantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btagregar.doClick();  //va sobre el boton aceptar
            btguardar.setEnabled(true);
        }
    }//GEN-LAST:event_txtcantidadKeyPressed

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped
        if (Character.isDigit(evt.getKeyChar()) == false) {
            evt.consume();
        }
        if (txtcantidad.getText().length() > 2) {  //ingresa hasta 4 digitos
            evt.consume();

        }
    }//GEN-LAST:event_txtcantidadKeyTyped

    private void btagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btagregarActionPerformed
        if (txtcodigo.getText().trim().isEmpty()) {  //si el campo esta vacio
            JOptionPane.showMessageDialog(null, "El campo esta vacio", "Error", JOptionPane.INFORMATION_MESSAGE);
            txtcodigo.requestFocus();

            return;
        }
        if (txtcantidad.getText().trim().isEmpty() || Integer.parseInt(txtcantidad.getText().trim()) <= 0) {
            JOptionPane.showMessageDialog(null, "Verifique los datos", "Error", JOptionPane.INFORMATION_MESSAGE);
            txtcantidad.requestFocus();

            return;
        }
        String iva5 = "1";
        String iva10 = "2";
        String ivaexenta = "3";
        int vcantidad = 0, vstock = 0;
        vcantidad = Integer.parseInt(txtcantidad.getText().trim());
        vstock = Integer.parseInt(txtstock.getText().trim());

        if (vcantidad > vstock) {
            JOptionPane.showMessageDialog(null, "La cantidad ingresada no puede ser mayor a su stock:.");
            txtcantidad.requestFocus();
            txtcantidad.setText("");
            return;
        }
        int vresultado = 0;
        vresultado = vstock - vcantidad;
        txtstock.setText(formateador.format(vresultado));
        int vsubtotal = Integer.parseInt(txtcantidad.getText()) * Integer.parseInt(txtprecio.getText().replace(".", ""));
        try {
            DefaultTableModel det = (DefaultTableModel) detalle.getModel();

            if (iva5.equals(txtimpuesto.getText())) {
                det.addRow(new Object[]{txtcodigo.getText(),
                    txtdescripcion.getText(),
                    txtcantidad.getText(),
                    txtprecio.getText(),
                    formateador.format(vsubtotal), 0, 0});
                calcular_total3(); //suma iva5

            } else if (iva10.equals(txtimpuesto.getText())) {
                det.addRow(new Object[]{txtcodigo.getText(),
                    txtdescripcion.getText(),
                    txtcantidad.getText(),
                    txtprecio.getText(),
                    0,
                    formateador.format(vsubtotal), 0});
                calcular_total2(); //suma iva 10

            }
            if (txtimpuesto.getText().equals(ivaexenta)) {

                det.addRow(new Object[]{txtcodigo.getText(),
                    txtdescripcion.getText(),
                    txtcantidad.getText(),
                    txtprecio.getText(),
                    0,
                    0,
                    formateador.format(vsubtotal)});
                calcular_total(); //suma exenta

            }

            txtcodigo.setText("");
            txtdescripcion.setText("");
            txtcantidad.setText("");
            txtprecio.setText("");
            txtimpuesto.setText("");
            txtcantidad.setEnabled(false);
            txtcodigo.requestFocus();
            txtstock.setText("");
            suma();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error" + e);
        }
    }//GEN-LAST:event_btagregarActionPerformed

    private void btquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btquitarActionPerformed
        if (detalle.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "No existe detalle", "Error", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (detalle.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar el detalle", "Atencion", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int mensaje = JOptionPane.showConfirmDialog(null, "Desea Quitar la fila seleccionada", "Atencion", JOptionPane.YES_NO_OPTION);
        if (mensaje == JOptionPane.YES_OPTION) {
            DefaultTableModel t = (DefaultTableModel) detalle.getModel();
            t.removeRow(detalle.getSelectedRow());  //fila seleccionada
            calcular_total3(); //suma iva5
            calcular_total2(); //suma iva 10
            calcular_total(); //suma exenta
            suma();
        }
    }//GEN-LAST:event_btquitarActionPerformed

    private void detalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detalleMouseClicked
        btquitar.setEnabled(true);
    }//GEN-LAST:event_detalleMouseClicked

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
        accion = "nuevo";
        bd.autonumerico("factura", "id_factura", txtn);
        txtidapertura.setText(menu_principal.txtidapertura.getText());
           txtidempleado.setText(menu_principal.txtidusuario.getText());
        txtfecha.setText(fec.format(new Date()));
        btnuevo.setEnabled(false);
        bteliminar.setEnabled(false);
        btagregar.setEnabled(false);
//      bd.deshabilitar_botones(btnuevo,  , bteliminar, btagregar);
        txtidclient.setEnabled(true);
        txtidclient.requestFocus();
        txtpresupuesto.setEnabled(true);
        cbforma.setEnabled(true);
        btcancelar.setEnabled(true);
        bd.retornar_ultimo("timbrado", "id_timbrado", txtidtimbrado);
        if (!txtidtimbrado.getText().isEmpty()) {
            recuperar_timbrado();
        }

    }//GEN-LAST:event_btnuevoActionPerformed

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed

        new Busqueda_Factura(null, true).setVisible(true);

        if (!txtn.getText().isEmpty()) {
            recuperar_datos();
        }
        if (txtn.getText().isEmpty()) {

        } else {

            int mensaje = JOptionPane.showConfirmDialog(null, "¿ Desea Anular Factura ?", "Atencion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            //si es 0 presiono la opcion de si, si es 1 no

            if (mensaje == 0) {
                if (Busqueda_Factura.tabla.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(null, "No hay ningun presupuesto para Eliminar");

                } else {

                    try {
                        String sql = "UPDATE factura\n"
                                + "   SET  id_estado=?\n"
                                + " WHERE id_factura=?;";
                        PreparedStatement update = bd.conexion.prepareStatement(sql);
                        update.setInt(2, Integer.parseInt(txtn.getText()));
                        update.setInt(1, 2);
                        update.execute();

                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Error al Anular");

                    }
                    try {
                        String sqlel = "DELETE FROM detalle_tipocobro\n"
                                + " WHERE id_factura= ?;";
                        PreparedStatement delete = bd.conexion.prepareStatement(sqlel);
                        delete.setInt(1, Integer.parseInt(txtn.getText()));
                        delete.execute();

                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Error al Anular");

                    }

                }
                btcancelar.setEnabled(true);
                btcancelar.doClick();
            }
            if (mensaje == 1) {
                btcancelar.setEnabled(true);
                btcancelar.doClick();
                btcancelar.doClick();
            }
        }
    }//GEN-LAST:event_bteliminarActionPerformed

    private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarActionPerformed
//        
        if (detalle.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Verifique los datos", "Atencion", JOptionPane.QUESTION_MESSAGE);
            return;
        }
        int mensaje = JOptionPane.showConfirmDialog(null, "Venta Confirmada", "Atencion", JOptionPane.YES_NO_OPTION);
        if (mensaje == JOptionPane.YES_OPTION) {
            bandera = 1;
            new tipocobro(null, true).setVisible(true);
//            tipocobro.txtmonto.setText(formateador.format(monto));

            bandera = 0;
        }

    }//GEN-LAST:event_btguardarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        accion = "";
        btnuevo.setEnabled(true);
        bteliminar.setEnabled(true);
        btagregar.setEnabled(true);
        deshabilitarcampos();
        btcancelar.setEnabled(false);
        btguardar.setEnabled(false);
        btagregar.setEnabled(false);
        btquitar.setEnabled(false);
        limpiarcampos();
        DefaultTableModel tab = (DefaultTableModel) detalle.getModel();
        tab.setRowCount(0);   //limpiamos las filas a cero
        txttotal.setText("0");
    }//GEN-LAST:event_btcancelarActionPerformed

    private void txtfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfacturaActionPerformed

    private void txtidtimbradoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidtimbradoKeyReleased

    }//GEN-LAST:event_txtidtimbradoKeyReleased

    private void txtfinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfinActionPerformed

    private void txtcodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btagregar.setEnabled(true);
            if (txtcodigo.getText().isEmpty()) {
                bandera = 1;
                new Busqueda_Mercaderia(null, true).setVisible(true);
                Busqueda_Mercaderia.txtbuscar.requestFocus();
                bandera = 0;
            } else {
                recuperar_mercaderia();
            }
        }
    }//GEN-LAST:event_txtcodigoKeyPressed

    private void txtcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoKeyTyped

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtpresupuestoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpresupuestoKeyPressed

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {

            if (txtpresupuesto.getText().isEmpty()) {
                bandera = 1;
                new Busqueda_Presupuesto(null, true).setVisible(true);
                Busqueda_Presupuesto.txtbuscar.requestFocus();
                bandera = 0;
            } else {
                recuperar_presupuesto();
            }
        }
    }//GEN-LAST:event_txtpresupuestoKeyPressed

    private void txtiddepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtiddepositoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtiddepositoActionPerformed

    private void txtiddepositoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtiddepositoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtiddepositoKeyPressed

    private void txtiddepositoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtiddepositoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtiddepositoKeyTyped

    private void btokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btokActionPerformed
        grabar();

    }//GEN-LAST:event_btokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btagregar;
    public static javax.swing.JButton btcancelar;
    public javax.swing.JButton bteliminar;
    public static javax.swing.JButton btguardar;
    public javax.swing.JButton btnuevo;
    protected static javax.swing.JButton btok;
    public javax.swing.JButton btquitar;
    private javax.swing.JComboBox<String> cbforma;
    public static javax.swing.JTable detalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private jcMousePanel.jcMousePanel jcMousePanel2;
    private jcMousePanel.jcMousePanel jcMousePanel3;
    public static javax.swing.JTable tipocobro;
    public static javax.swing.JTextField txtcantidad;
    public static javax.swing.JTextField txtcliente;
    public static javax.swing.JTextField txtcodigo;
    public static javax.swing.JTextField txtdeposito;
    public static javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtdetmonto;
    public static javax.swing.JTextField txtdireccion;
    public static javax.swing.JTextField txtempleado;
    public javax.swing.JTextField txtexenta;
    public static javax.swing.JTextField txtfactura;
    public static javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtfin;
    public static javax.swing.JTextField txtidapertura;
    private javax.swing.JTextField txtidbanco;
    public static javax.swing.JTextField txtidclient;
    private javax.swing.JPanel txtidcliente;
    public static javax.swing.JTextField txtiddeposito;
    public static javax.swing.JTextField txtidempleado;
    public static javax.swing.JTextField txtidtimbrado;
    public static javax.swing.JTextField txtimpuesto;
    private javax.swing.JTextField txtinicio;
    public javax.swing.JTextField txtiva10;
    public javax.swing.JTextField txtiva5;
    public static javax.swing.JTextField txtn;
    private javax.swing.JTextField txtnroboleta;
    public static javax.swing.JTextField txtprecio;
    public static javax.swing.JTextField txtpresupuesto;
    public static javax.swing.JTextField txtruc;
    public static javax.swing.JTextField txtstock;
    public javax.swing.JTextField txtsub10;
    public javax.swing.JTextField txtsub5;
    private javax.swing.JTextField txtsumatim;
    public static javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txttimbrado;
    public static javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

    private void recuperar_timbrado() {
        try {
            bd.listar_datos("SELECT id_timbrado, tim_numero, tim_fechainicio, tim_fechavencimiento, \n"
                    + "       inicio, ultimo, actual\n"
                    + "  FROM timbrado"
                    + " where id_timbrado =" + txtidtimbrado.getText()
                    + "");
            if (bd.resultado.next()) {
                txttimbrado.setText(bd.resultado.getString("tim_numero"));

                txtinicio.setText(bd.resultado.getString("tim_fechainicio"));
                txtfin.setText(bd.resultado.getString("tim_fechavencimiento"));
                txtidbanco.setText(bd.resultado.getString("inicio"));
                txtnroboleta.setText(bd.resultado.getString("ultimo"));
                txtfactura.setText(bd.resultado.getString("actual"));

            } else {
                JOptionPane.showMessageDialog(null, "No existe codigo\nPor favor verifique", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al recuperar timbrado",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }

    private void recuperar_cliente() {
        try {
            bd.listar_datos("SELECT id_cliente, id_ciudad, cli_nombre, cli_ci, cli_ruc, cli_direc, \n"
                    + "       cli_telef, id_estado\n"
                    + "  FROM cliente"
                    + " where id_cliente =" + txtidclient.getText()
                    + "");
            if (bd.resultado.next()) {
                txtcliente.setText(bd.resultado.getString("cli_nombre"));
                txtruc.setText(bd.resultado.getString("cli_ruc"));
                txtdireccion.setText(bd.resultado.getString("cli_direc"));
                txttelefono.setText(bd.resultado.getString("cli_telef"));
                txtcodigo.setEnabled(true);
                txtcodigo.requestFocus();

            } else {
                JOptionPane.showMessageDialog(null, "No existe codigo ingresado\nPor favor verifique", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al recuperar cliente",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }

    private void recuperar_mercaderia() {
        try {
            bd.listar_datos("SELECT s.id_articulo as codigo,  s.stock_cant as cantidad, a.art_descri as descripcion,"
                    + "a.art_precioc as precio , a.id_impuesto as impuesto\n"
                    + "  FROM stock s inner join articulos a on a.id_articulo= s.id_articulo"
                    + " where s.id_articulo =" + txtcodigo.getText());
            if (bd.resultado.next()) {
                for (int i = 0; i < detalle.getRowCount(); i++) {
                    String vcod = detalle.getValueAt(i, 0).toString();
                    if (vcod.equals(txtcodigo.getText())) {
                        JOptionPane.showMessageDialog(null, "Codigo Ingresado ya Existe", "Error", JOptionPane.ERROR_MESSAGE);
                        txtcodigo.requestFocus();
                        txtcodigo.setSelectionStart(0);
                        return;
                    }
                }
                txtdescripcion.setText(bd.resultado.getString("descripcion"));
                txtprecio.setText(formateador.format(bd.resultado.getInt("precio")));
                txtimpuesto.setText(bd.resultado.getString("impuesto"));
                txtstock.setText(bd.resultado.getString("cantidad"));
                txtcantidad.setEnabled(true);
                txtcantidad.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "No existe codigo ingresado\nPor favor verifique", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al recuperar mercaderia",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }

    private void calcular_total3() {
        int vtot5 = 0;
        for (int i = 0; i < detalle.getRowCount(); i++) {
            //Toma el monto de la columna sub total en la variable vtot
            int vtot = Integer.parseInt(detalle.getValueAt(i, 4).toString().replace(".", ""));
            vtot5 = vtot5 + vtot;
//             vtotexe += vtot;
        }
        txtsub5.setText(formateador.format(vtot5));

    }

    private void calcular_total2() {
        int vtot10 = 0;
        for (int i = 0; i < detalle.getRowCount(); i++) {
            //Toma el monto de la columna sub total en la variable vtot
            int vtot = Integer.parseInt(detalle.getValueAt(i, 5).toString().replace(".", ""));
            vtot10 = vtot10 + vtot;
//             vtot10 += vtot;
        }
        txtsub10.setText(formateador.format(vtot10));

    }

    private void calcular_total() {
        int vexenta = 0;
        for (int i = 0; i < detalle.getRowCount(); i++) {
            //Toma el monto de la columna sub total en la variable vtot
            int vtot = Integer.parseInt(detalle.getValueAt(i, 6).toString().replace(".", ""));
            vexenta = vexenta + vtot;
//             vtot5 += vtot;
        }
        txtexenta.setText(formateador.format(vexenta));

    }

    private void suma() {
        int v5 = 0;
        int v10 = 0;
        int vexe = 0;
        int vsuma = 0;

        v5 = Integer.parseInt(txtsub5.getText().replace(".", ""));
        v10 = Integer.parseInt(txtsub10.getText().replace(".", ""));
        vexe = Integer.parseInt(txtexenta.getText().replace(".", ""));
        vsuma = v5 + v10 + vexe;

        txtiva5.setText(formateador.format(v5 / 21));
        txtiva10.setText(formateador.format(v10 / 11));
        txttotal.setText(formateador.format(vsuma));

    }

    private void recuperar_presupuesto() {
        DefaultTableModel dt = (DefaultTableModel) detalle.getModel();
        dt.setRowCount(0);
        try {
            bd.listar_datos("SELECT presupuesto, codigo, articulo, idpresudet, cantidad, exenta, \n"
                    + "       iva5, iva10, precio, fecha, cliente, nombre, ruc, direccion, \n"
                    + "       telefono, monto, estado\n"
                    + "  FROM v_presupuessto  where estado=1 and(presupuesto=" + txtpresupuesto.getText() + ");");
            if (bd.resultado.next()) {
                txtfecha.setText(fec.format(bd.resultado.getDate("fecha")));
                txtidclient.setText(bd.resultado.getString("cliente"));
                txtcliente.setText(bd.resultado.getString("nombre"));
                txtruc.setText(bd.resultado.getString("ruc"));
                txtdireccion.setText(bd.resultado.getString("direccion"));
                txttelefono.setText(bd.resultado.getString("telefono"));

                do {
                    dt.addRow(new Object[]{bd.resultado.getString("codigo"),
                        bd.resultado.getString("articulo"),
                        bd.resultado.getString("cantidad"),
                        formateador.format(bd.resultado.getInt("precio")),
                        formateador.format(bd.resultado.getInt("iva5")),
                        formateador.format(bd.resultado.getInt("iva10")),
                        formateador.format(bd.resultado.getInt("exenta")),});
                } while (bd.resultado.next());
                calcular_total();
                calcular_total2();
                calcular_total3();
                suma();
                btguardar.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al recuperar datos" + e);
        }
    }

    private void grabar() {
        if (accion.equals("nuevo")) {
            try {
                //grabar la cabecera
                String sqlcabecera = "INSERT INTO factura(id_factura, id_timbrado, id_usuario, id_cliente, id_presupuesto, \n"
                        + "            id_apertura, id_deposito, fact_numero, fact_fecha, fact_tipo, \n"
                        + "            fact_monto, id_estado)\n"
                        + "    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
                PreparedStatement cabecera = bd.conexion.prepareStatement(sqlcabecera);
                cabecera.setInt(1, Integer.parseInt(txtn.getText()));
                cabecera.setInt(2, Integer.parseInt(txtidtimbrado.getText()));
                cabecera.setInt(3, Integer.parseInt(txtidempleado.getText()));
                cabecera.setInt(4, Integer.parseInt(txtidclient.getText()));
                cabecera.setInt(5, Integer.parseInt(txtpresupuesto.getText()));
                cabecera.setInt(6, Integer.parseInt(txtidapertura.getText()));
                cabecera.setInt(7, Integer.parseInt(txtiddeposito.getText()));
                cabecera.setString(8, txtfactura.getText());
                cabecera.setDate(9, java.sql.Date.valueOf(convertir_fecha(txtfecha.getText())));
                cabecera.setString(10, txttotal.getText());
                cabecera.setString(11, txttotal.getText());
                cabecera.setInt(12, 1);
                cabecera.execute();

                //grabar detalle
                String sqldetalle = "INSERT INTO detalle_factura(id_articulo, idfacdet, id_factura, det_cant, det_exenta, det_iva5, \n"
                        + "            det_iva10, det_precio,id_deposito)\n"
                        + "    VALUES (?, ?, ?, ?, ?, ?, ?, ?,?);";
                for (int i = 0; i < detalle.getRowCount(); i++) {
                    String vcodigo = detalle.getValueAt(i, 0).toString();  //0 la columna
                    String vcantidad = detalle.getValueAt(i, 2).toString(); // 2 la columna
                    String vprecio = detalle.getValueAt(i, 3).toString().replace(".", "");    //remplaza el separador de miles
                    String vcinco = detalle.getValueAt(i, 4).toString().replace(".", "");
                    String vdiez = detalle.getValueAt(i, 5).toString().replace(".", "");
                    String vexenta = detalle.getValueAt(i, 6).toString().replace(".", "");
                    grabar_detalle(sqldetalle, vcodigo, vcantidad, vprecio, vcinco, vdiez, vexenta);

                }

                // inser datos de tipo de cobro 
                String sqltipo = " INSERT INTO detalle_tipocobro(\n"
                        + "            id_factura, id_tipo, id_banco, nro_boleta, det_monto)\n"
                        + "    VALUES (?, ?, ?, ?, ?);";
                PreparedStatement tipo = bd.conexion.prepareStatement(sqltipo);
                for (int i = 0; i < tipocobro.getRowCount(); i++) {
                    String vfac = tipocobro.getValueAt(i, 0).toString();  //0 la columna
                    String vtipo = tipocobro.getValueAt(i, 1).toString(); // 2 la columna
                    String vbanco = tipocobro.getValueAt(i, 2).toString();    //remplaza el separador de miles
                    String vboleta = tipocobro.getValueAt(i, 3).toString();    //remplaza el separador de miles
                    String vmonto = tipocobro.getValueAt(i, 4).toString().replace(".", "");
                    grabar_det(sqltipo, vfac, vtipo, vbanco, vboleta, vmonto);
                }
                //actualizamos pedido_presupuesto
                String sqlpre = "UPDATE pedido_presupuesto\n"
                        + "   SET id_estado=?\n"
                        + " WHERE id_presupuesto=?;";
                PreparedStatement pre = bd.conexion.prepareStatement(sqlpre);
                pre.setInt(2, Integer.parseInt(txtpresupuesto.getText()));
                pre.setInt(1, 3);
                pre.execute();

                btcancelar.doClick();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "error al grabar" + ex);
            }
        } else {
            //insert
        }

    }

    private void deshabilitarcampos() {
        txtidclient.setEnabled(false);
        txtcodigo.setEnabled(false);
        txtpresupuesto.setEnabled(false);
        txtcantidad.setEnabled(false);

    }

    private void limpiarcampos() {
        txtn.setText("");
        txtfecha.setText("");
        txtidclient.setText("");
        txtruc.setText("");
        txtdireccion.setText("");
        txttelefono.setText("");
        txtpresupuesto.setText("");
        txtcodigo.setText("");
        txtcliente.setText("");
        txttimbrado.setText("");
        txtinicio.setText("");
        txtfin.setText("");
        txtdescripcion.setText("");
        txtprecio.setText("");
        txtcantidad.setText("");
    }

    private String convertir_fecha(String fecha) {
        // 25-08-2016
        String dia = "", mes = "", anho = "";

        dia = fecha.substring(0, 2);
        mes = fecha.substring(3, 5);
        anho = fecha.substring(6, 10);
        fecha = anho + "-" + mes + "-" + dia;

        return fecha;
    }

    private void grabar_detalle(String sqldetalle, String vcodigo, String vcantidad, String vprecio, String vcinco, String vdiez, String vexenta) {
        int vidventa = 0;
        try {
            bd.listar_datos("select nextval('idventadetalle')as codigo");
            bd.resultado.next();
            vidventa = bd.resultado.getInt("codigo");
        } catch (Exception e) {
        }
        try {
            PreparedStatement detalle1 = bd.conexion.prepareStatement(sqldetalle);
            detalle1.setInt(3, Integer.parseInt(txtn.getText()));
            detalle1.setInt(2, vidventa);
            detalle1.setInt(1, Integer.parseInt(vcodigo));
            detalle1.setInt(4, Integer.parseInt(vcantidad));
            detalle1.setInt(5, Integer.parseInt(vexenta));
            detalle1.setInt(6, Integer.parseInt(vcinco));
            detalle1.setInt(7, Integer.parseInt(vdiez));
            detalle1.setInt(8, Integer.parseInt(vprecio));
            detalle1.setInt(9, Integer.parseInt(txtiddeposito.getText()));
            detalle1.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al grabar detalle" + e);
        }
    }

    private void grabar_det(String sqltipo, String vfac, String vtipo, String vbanco, String vboleta, String vmonto) {
        try {
            PreparedStatement dettipo = bd.conexion.prepareStatement(sqltipo);
            dettipo.setInt(1, Integer.parseInt(vfac));
            dettipo.setInt(2, Integer.parseInt(vtipo));
            dettipo.setInt(3, Integer.parseInt(vbanco));
            dettipo.setInt(4, Integer.parseInt(vboleta));
            dettipo.setInt(5, Integer.parseInt(vmonto));
            dettipo.execute();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al grabar tipocobro" + e);
        }

    }

    private void recuperar_datos() {
        DefaultTableModel dta = (DefaultTableModel) detalle.getModel();
        dta.setRowCount(0);
        try {
            bd.listar_datos("SELECT factura, timbrado, usuario, cliente, clientenombre, ruc, direccion, \n"
                    + "       telefono, presupuesto, apertura, facturanumero, fecha, tipo, \n"
                    + "       monto, estato, codigo, descripcion, idfacdet, cantidad, exenta, \n"
                    + "       iva5, iva10, precio, deposito\n"
                    + "  FROM v_factura where estato=1 and(factura=" + txtn.getText() + ");");
            if (bd.resultado.next()) {
                txtfecha.setText(fec.format(bd.resultado.getDate("fecha")));
                txtidclient.setText(bd.resultado.getString("cliente"));
                txtcliente.setText(bd.resultado.getString("clientenombre"));
                txtruc.setText(bd.resultado.getString("ruc"));
                txtdireccion.setText(bd.resultado.getString("direccion"));
                txttelefono.setText(bd.resultado.getString("telefono"));

                do {
                    dta.addRow(new Object[]{bd.resultado.getString("codigo"),
                        bd.resultado.getString("descripcion"),
                        bd.resultado.getString("cantidad"),
                        formateador.format(bd.resultado.getInt("precio")),
                        formateador.format(bd.resultado.getInt("iva5")),
                        formateador.format(bd.resultado.getInt("iva10")),
                        formateador.format(bd.resultado.getInt("exenta")),});
                } while (bd.resultado.next());
                calcular_total();
                calcular_total2();
                calcular_total3();
                suma();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al recuperar datos" + e);
        }

    }
}
